### ISSUE TITLE
Show changelog on update

### ISSUE THREAD

**Issue by vprelovac** [Aider-AI/aider#1266]
### Issue

auto update is very cool. There is opportunity to print changelog right there:
```
Newer aider version v0.54.8 is available. To upgrade, run:

/bin/python3.11 -m pip install --upgrade aider-chat
Run pip install? (Y)es/(N)o [Yes]:

Installing:  /bin/python3.11 -m pip install --upgrade aider-chat
                
Installation complete.

Re-run aider to use new version.

Changelog:
- item1
- item2
```

**Comment by 5ocworkshop** [comment]
Excellent suggest.  I would appreciate this.

**Comment by fry69** [comment]
In the meantime the changelog is also available here -> https://aider.chat/HISTORY.html

**Comment by paul-gauthier** [comment]
This has been available in recent versions. 

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
