### ISSUE TITLE
Default model for reasoning tasks

### ISSUE THREAD

**Issue by aerugo** [Aider-AI/aider#1517]
### Issue

When starting new modules or projects with Aider, I usually start with a chat session where I ask Aider to create a step by step plan. It might look like this: 
[Frontend Implementation Plan.md](https://github.com/user-attachments/files/16992021/Frontend.Implementation.Plan.md)
After the completion of each step, I will usually direct Aider back to the implementation plan and move to the next step. Given that the implementation details of each step may change the plan for future steps, I will usually go to chat mode and ask Aider to make a more detailed plan for the next step of the implementation based on a conversation about the current state of the project, then go back to code mode and ask Aider to update the implementation plan.

Reasoning models like o1 are well suited for this sort of work. I would prefer to be able to use a reasoning model like GPT o1 in chat mode, while using sonnet-3.5 in code mode, and something cheaper for the weak model.

A related idea would be better built-in support for implementation plans, but that's a different issue.

**Comment by tom130** [comment]
good idea, I think you can still  do the ask mode to "think" about the plan and then code mode to implement the changes via sonnet. But haven't tried this model changes in the middle of conversation/coding

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `/model` to change the model during the chat.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
