### ISSUE TITLE
Feature request: play nice with external editing

### ISSUE THREAD

**Issue by jbellis** [Aider-AI/aider#1533]
### Issue

My aider workflow is
1. Ask aider to make a change
2. Review changes, often I make changes to what Claude came up with
3. Repeat

Currently I have to /drop and re-/add files that I changed in my IDE.  Could aider automatically reload files that changed on disk since its last edit?  I'm happy to take a stab at this.

### Version and model info

Aider v0.56.0

**Comment by fry69** [comment]
aider loads all files that are part of the context before sending them to the LLM fresh from the disk. They do not get stored in memory. So if you make changes outside aider, they will be reflected the next time you send a prompt to the LLM.

**Comment by jbellis** [comment]
I guess it needs to check earlier then, because the changes are definitely not visible for tab completion unless I manually drop and add.

**Comment by fry69** [comment]
The changes may not be visible to autocomplete, but the files get read from disk before they get sent to the LLM.

As long as the files are part of the repository, aider will see and know them. If possible, commit your changes after editing them from outside before you switch to aider again.

**Comment by jbellis** [comment]
You're right, it's reloading before sending to the LLM.  Only autocomplete gets confused.

**Comment by paul-gauthier** [comment]
You could also just press ENTER in aider to start a new blank prompt. That will refresh the autocompleter.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
