### ISSUE TITLE
Feature request: flag unused context

### ISSUE THREAD

**Issue by jbellis** [Aider-AI/aider#1538]
### Issue

I just spent a large chunk of my Claude balance when I accidentally left a 5,000 line file in the context after I was done editing it.  I eventually noticed my mistake when I wondered why aider/Claude was taking longer to respond than expected.  (This is not how I prefer to organize things but it was someone else's project.)  What do you think about adding a line to the output like this?

> Applied edit to foo.py
> Unedited files in context: bar.py, baz.py

### Version and model info

Aider v0.56.0

**Comment by fry69** [comment]
If you are unsure what is in your context, you can use `/tokens` to check.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider already shows all the files in the context above each prompt:

```
─────────────────────────
aider/scrape.py
>
```
