### ISSUE TITLE
Allowing Aider to use an API-based Tool to get additional context

### ISSUE THREAD

**Issue by JeongJuhyeon** [Aider-AI/aider#1540]
### Issue

Hi, first of all, Aider's an absolutely brilliant tool and highly competitive with big tech and SV backed tools, kudos!

## Context

It would be super useful to be able to give "If you need some inspiration, look at www.example.com/code-examples-for-some-library" as Conventions. This would require ability not just to get the HTML of a certain page, but possibly traverse links, and so on. You may quickly reach a point where such functionality feels out of scope for Aider. But there are plenty of tools being used for this kind of purpose, including in the form of a REST API. So if Aider could send an HTTP request to www.codeexamples.com, with a description of the kind of information it's looking for, and then add the result to its context, that would be brilliant.

While opinions on the idea of "multi-agent frameworks" vary, Aider is so strong as an engineering "agent" that it could really benefit from being able to interact with other, specialized LLM-based tools.

## Potential small initial feature

An initial great step would be if we could just add 20 URLs to the conventions and then have Aider pick and visit one if it thinks it needs it.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `/web` to add a URL to the context. This doc may be helpful:

https://aider.chat/docs/usage/images-urls.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
