### ISSUE TITLE
Any way to output the repo-map?

### ISSUE THREAD

**Issue by vlrevolution** [Aider-AI/aider#1564]
### Issue

I'd love to see the repo-map, how to display/copy it?

### Version and model info

latest

**Comment by fry69** [comment]
You can output the repository map with `aider --show-repo-map`, see here -> https://aider.chat/docs/config/options.html#--show-repo-map

**Comment by vlrevolution** [comment]
Thanks!

**Comment by vlrevolution** [comment]
I am a bit confused by how the map is created. It is adding things there that are not even added as files. I add /src but it is shopwing stuff from root dir and actually nothing from /src

could you explain how to understand the map?

**Comment by fry69** [comment]
This document may help -> https://aider.chat/docs/repomap.html

**Comment by vlrevolution** [comment]
I read it but it doesn't say anything about added files vs non added files

**Comment by paul-gauthier** [comment]
Files you add to the chat are NOT part of the repo map. Because the repo map only shows things which aren't in the chat.

**Comment by vlrevolution** [comment]
I see, that actually does make a lot of sense :D

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
