### ISSUE TITLE
REQ: A new file type "ask2edit" to complement read only and regular file loads

### ISSUE THREAD

**Issue by 5ocworkshop** [Aider-AI/aider#1567]
I wanted to propose an additional type of file for aider to load in to the conversation.  I'm sure we can come up with a more elegant name, but for now I'll call it "ask2edit".

At the moment we can load files that are editable, or we can load files that are read only and use Sonnet's cache mechanism.

The purpose of the ask2edit load type would be that the file can be edited by the LLM but the LLM doesn't have carte blanche to make changes, instead it should only make changes when the user has reviewed and approved them.

Working through a larger project I'm refining my process of product requirements, architecture, design and implementation planning and then proceeding with coding and debugging.  As is the norm during development, adjustments to the product requirements and related cascading changes will need to be made.  However the LLMs have a habit of removing or altering things we may not want to have altered in the requirements or design documents, when trying to update them to reflect additions or changes that happen during development.

As part of my conventions.md I would like to tell the LLM that when we materially update or enhance a feature that is mentioned in the product requirements document, also update that requiremetns document so it stays in sync with the project code as built.  However, I would like the LLM to present the current version of the relevant section and the proposed changes while identifying the file it wants to change - then have it ask whether it can make those changes or allow me to iterate and request updates to the proposed wording.  This way we could iterate on a the wording changes before the edits take place.

So with ask2edit files, the idea is that the file shouldn't be updated during normal operations to avoid it accidentally being modified during the development cycle when it was meant purely as a reference but when the LLM is asked to perform an explicit operation on that file, draft wording and present it for approval or dialog.

**Comment by fry69** [comment]
Thank you for filing this issue.

You can add all files you need as read-only with `/read` first and then move select ones to a writable state `/add`.

**Comment by 5ocworkshop** [comment]
That is a possible work around but not quite what I'm envisioning.  I'll sleep on it and see if I can explain it more clearly.
