### ISSUE TITLE
REQ: Add explicit-command chat mode

### ISSUE THREAD

**Issue by dmurat** [Aider-AI/aider#1569]
### Issue

On numerous occasions, I forgot to add a slash in front of the aider command, which resulted in sending a request to LLM. I think it would be useful to have an `explicit-command` chat mode that will not do anything unless the prompt is prefixed with an aider command (/ask, /code, or any other).

### Version and model info

Aider v0.56.0
Model: deepseek/deepseek-coder with diff edit format, prompt cache, infinite output
Git repo: .git with 246 files
Repo-map: using 2048 tokens, files refresh

**Comment by fry69** [comment]
Maybe related #1315

**Comment by dmurat** [comment]
I can see similarities, but I think it is still different. 

I'm looking for an explicit option to allow communication towards LLM. It can be either an explicit command, as I mentioned before. It can be an option to automatically add a slash in front of each Aider input. It can be an Aider question to the user to allow communication, or something similar.

Tnx

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I'm not sure this is likely to be in the roadmap for aider.

**Comment by dmurat** [comment]
Ok, I understand. Tnx, anyway.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
