### ISSUE TITLE
Lint in subdir in monorepo

### ISSUE THREAD

**Issue by mrclrchtr** [Aider-AI/aider#1579]
### Issue

Hi,

first of all, thank you very much for the great tool!

I use aider in a monorepo in which there is a subdirectory for the frontend. I will call it `subdir` in the further course.

I would like to specify a `lint-cmd` (`yarn run lint`). Unfortunately aider tries to execute the cmd in the root folder and not in the `subdir`. This then fails because there is no `package.json` etc. in the root.

If I set `lint-cmd: “yarn --cwd subdir run lint"`, then unfortunately the paths of the files are no longer correct, because aider thinks that the command is executed in the root dir and appends the `subdir` before the file:

Example:
`## Running: yarn --cwd subdir run lint subdir/package.json`

Is there a way to change the root dir in which commands are executed? 
I currently start aider in subdir. Aider recognizes that `git-root` is in the parent: 
`Git repo: ../.git with 217 files`

Thank you very much!

### Version and model info

```
sonnet: true
lint: true
lint-cmd: ["yarn --cwd subdir run lint"]
subtree-only: true
```

Aider v0.56.0
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You could make a small shell script "mylinter.sh" that does does the `cd` and/or modifies the filepaths before invoking the linter.

**Comment by mrclrchtr** [comment]
Thank you very much for the answer and your support. I'm having more and more fun using aider from day to day.

That is definitely a possibility for lint. However, I have now encountered another problem: Sometimes aider wants to execute other commands. For example, when it wants to install new packages with yarn. This is also executed in the root folder and not in the subdir. 

I think it would make sense to add an option that allows you to change the root directory. Or the root directory in which commands are executed could by default be the subdirectory in which aider is executed?

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by tino** [comment]
I would indeed expect a `--working-directory` option or so. Having to write separate shell scripts for aider for each service in my monorepo isn't very enticing. Running with `--no-git` doesn't change this for some reason?
