### ISSUE TITLE
Repo scan quits Aider

### ISSUE THREAD

**Issue by paul-hammant** [Aider-AI/aider#1606]
### Issue

I've read #1587 but this is different.  Aider quits completely for this repo.

To reproduce:

```
git clone git@github.com:bytedeco/javacpp-presets.git
cd javacpp-presets/
aider
/add .github/ 
update modsecurity.yml to latest base images like scipy.yml has been
```

You'll be back at the command line, Aider having quit

I read https://it.slashdot.org/story/24/09/19/1721236/1-in-10-orgs-dumping-their-security-vendors-after-crowdstrike-outage and thought I'd have another go at more methodically upgrading the modsecurity within this excellent technoloy

### Version and model info

aider 0.56.0

(using OpenAI remotely)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Can you share a screenshot of the problem, so I can see any output associated with the crash?

This looks like a very large repo. This doc may be helpful:

https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo

**Comment by paul-hammant** [comment]
![image](https://github.com/user-attachments/assets/7751fb9e-c858-457f-84ac-991e9b180c08)

I tried a `--depth 10` clone, in case it was the weight of history Aider was choking on, but no.

**Comment by paul-hammant** [comment]
Launching again with `--subtree-only .github/`

Aider command: `/add .github/ only`

Aider Command upgrade the modsecurity.yml to be like was recently done for pytorch.yml

![image](https://github.com/user-attachments/assets/42e2828b-c453-4f48-9a3c-07793d027dbd)

**Comment by paul-gauthier** [comment]
To work in a subtree you change directories into the subtree before launching aider, then add the `--subtree-only` switch. It does not take a dirname as an argument.

Some file in that repo is probably crashing tree-sitter.

If you cd into `.github` and run `aider --subtree-only` you can probably work around this problem.

**Comment by paul-gauthier** [comment]
I think the problem was simply that you ran out of memory processing this repo with 12k files! I cloned it and my aider isn't quitting, but is struggling with memory use.

Use `--subtree-only` as described above when working with such large repos.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
