### ISSUE TITLE
aider error Unexpected value for AIDER_DEEPSEEK

### ISSUE THREAD

**Issue by BeraBravo** [Aider-AI/aider#1614]
### Issue

aider only working with DEEPSEEK model

I tried to use gemini or sonnet and I got the error for both 

aider --model gemini/gemini-1.5-pro-latest
aider --opus
aider --model ollama/llama3:8b

aider: error: Unexpected value for AIDER_DEEPSEEK: 'sk-95...the rest of deepseek API KEY'. Expecting 'true', 'false', 'yes', 'no', 'on', 'off', '1' or '0'

I followed the instructions of the documentation and exported in the bash shell each key api above

https://aider.chat/docs/llms/

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The `AIDER_DEEPSEEK` varible is an alias for `--deepseek` which means "use the deepseek model".

https://aider.chat/docs/config/options.html#--deepseek

Looks like you put your API key in it. That belongs in `DEEPSEEK_API_KEY`. This doc may be helpful:

https://aider.chat/docs/llms/deepseek.html

**Comment by fry69** [comment]
I'm closing this issue for now.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
