### ISSUE TITLE
added hashes to a folder name

### ISSUE THREAD

**Issue by aldoyh** [Aider-AI/aider#1618]
Hello guys,

Thank you for such an amazing tool.

I've just started "knowing" how to use it, but whenever I add a certain folder using the `/add lib\` it adds 3 hashes to it, is this intentional or can be fixed?

![Screenshot 2024-09-21 at 11 54 22](https://github.com/user-attachments/assets/687c4ecb-6020-47eb-a35a-83716d484557)

Aider version: 0.56.0
Python version: 3.10.14
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.46.1

Aider v0.56.0
Model: mistral/mistral-large-latest with whole edit format, infinite output
Git repo: .git with 224 files
Repo-map: disabled
Added ### lib/api/service.dart to the chat.
Added ### lib/auction_details_screen.dart to the chat.
Added ### lib/controllers/auction_controller.dart to the chat.
Added ### lib/controllers/auth_controller.dart to the chat.
Added ### lib/flip_down_timer.dart to the chat.
Added ### lib/home4.dart to the chat.
Added ### lib/home_alternative.dart to the chat.
Added ### lib/home_screen.dart to the chat.
Added ### lib/main.dart to the chat.
Added ### lib/models/auction.dart to the chat.
Added ### lib/models/auction.g.dart to the chat.
Added ### lib/models/bid.dart to the chat.
Added ### lib/models/transaction.dart to the chat.
Added ### lib/models/user.dart to the chat.
Added ### lib/models/user.g.dart to the chat.
Added ### lib/post_list.dart to the chat.
Added ### lib/screens/auction_details_screen.dart to the chat.
Added ### lib/screens/profile_screen.dart to the chat.
Added ### lib/user.dart to the chat.
Added ### lib/views/auction_carousel.dart to the chat.
Added ### lib/views/auction_list.dart to the chat.
Added ### lib/widgets/auctions_closed.dart to the chat.
Added ### lib/widgets/flip_down_timer.dart to the chat.
Added ### lib/widgets/inactive_auctions_list.dart to the chat.
Added ### lib/widgets/main_web_nav.dart to the chat.
Added lib/api/service.dart to the chat.
Added lib/auction_details_screen.dart to the chat.
Added lib/controllers/auction_controller.dart to the chat.
Added lib/controllers/auth_controller.dart to the chat.
Added lib/flip_down_timer.dart to the chat.
Added lib/home4.dart to the chat.
Added lib/home_alternative.dart to the chat.
Added lib/home_screen.dart to the chat.
Added lib/main.dart to the chat.
Added lib/models/auction.dart to the chat.
Added lib/models/auction.g.dart to the chat.
Added lib/models/bid.dart to the chat.
Added lib/models/transaction.dart to the chat.
Added lib/models/user.dart to the chat.
Added lib/models/user.g.dart to the chat.
Added lib/post_list.dart to the chat.
Added lib/screens/auction_details_screen.dart to the chat.
Added lib/screens/profile_screen.dart to the chat.
Added lib/user.dart to the chat.
Added lib/views/auction_carousel.dart to the chat.
Added lib/views/auction_list.dart to the chat.
Added lib/widgets/auctions_closed.dart to the chat.
Added lib/widgets/flip_down_timer.dart to the chat.
Added lib/widgets/inactive_auctions_list.dart to the chat.
Added lib/widgets/main_web_nav.dart to the chat.
Restored previous conversation history.

**Comment by fry69** [comment]
Thank you for filing this issue.

The model you used `mistral/mistral-large-latest` may not be able to produce the correct format aider needs to work effectively. Try using a better model (current go-to recommendation is Sonnet-3.5).

See also the model leaderboard -> https://aider.chat/docs/leaderboards/

Also this documentation may be helpful -> https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by fry69** [comment]
@aldoyh

There is a fix in the current `main` branch that might help you with this problem, see here -> https://github.com/paul-gauthier/aider/commit/54cfbc4142e10dde73434accd20761bfc1ba3f1e

You can install the `main` branch with ->
```shell
aider --install-main-branch

# or

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```
If you have a chance to try it, please report if it works better for you.

**Comment by aldoyh** [comment]
Thank you so much guys for your replies it did actually work just like a charm!
And I did go back to the local installation of a ollama/mistral AND Mistral/Mistral also worked perfectly!

Now my question is **should I stay on the current branch or should I go back to the main?**

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
