### ISSUE TITLE
Uncaught TypeError in repomap.py line 665

### ISSUE THREAD

**Issue by jonsrose** [Aider-AI/aider#1665]
Aider version: <module 'aider.__version__' from '/opt/anaconda3/lib/python3.11/site-packages/aider/__version__.py'>
Python version: 3.11.7
Platform: macOS-10.16-x86_64-i386-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 22.6.0 (64bit)
Git version: git version 2.39.3 (Apple Git-145)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 709, in main
    coder.run()
  File "base_coder.py", line 723, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 766, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1097, in send_message
    chunks = self.format_messages()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 1035, in format_messages
    chunks = self.format_chat_chunks()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 985, in format_chat_chunks
    chunks.repo = self.get_repo_messages()
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 620, in get_repo_messages
    repo_content = self.get_repo_map()
                   ^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 602, in get_repo_map
    repo_content = self.repo_map.get_repo_map(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 127, in get_repo_map
    files_listing = self.get_ranked_tags_map(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 478, in get_ranked_tags_map
    result = self.get_ranked_tags_map_uncached(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 509, in get_ranked_tags_map_uncached
    ranked_tags = self.get_ranked_tags(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 342, in get_ranked_tags
    tags = list(self.get_tags(fname, rel_fname))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 198, in get_tags
    data = list(self.get_tags_raw(fname, rel_fname))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 221, in get_tags_raw
    query_scm = get_scm_fname(lang)
                ^^^^^^^^^^^^^^^^^^^
  File "repomap.py", line 665, in get_scm_fname
    return resources.files(__package__).joinpath("queries", f"tree-sitter-{lang}-tags.scm")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MultiplexedPath.joinpath() takes 2 positional arguments but 3 were given

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please check how you installed aider and report the version number (e.g. the first few lines when aider starts up)? It seems there is something wrong somewhere.

In doubt, try reinstalling aider with one of the official methods (not via system packages and `homebrew`, they often have problems getting dependencies right, among other things).

See here for installation instructions -> https://aider.chat/docs/install/install.html

**Comment by dwiel** [comment]
I get this problem when I try to install via `pip install -e .` but it works fine if I use `pip install aider-chat`. I'd like to modify aider though, so would be nice to have it work from the repo itself. How are devs otherwise setting up their environment?

**Comment by paul-gauthier** [comment]
You probably have incorrect versions of some dependencies installed. You probably need to start from a *clean* virtual environment before doing the `pip install -e .`

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
