### ISSUE TITLE
Bug report: Offered to add the wrong file to the chat instead of creating a new one

### ISSUE THREAD

**Issue by niradar** [Aider-AI/aider#1723]
### Issue

When asking to create a new file, the LLM understood correctly what I want to do, but aider offered the wrong action.

Steps

--1--
I have:
- README.me on project root
- scripts/ folder with several scripts

--2--
I added all the scripts to the chat using :
/read-only scripts/

--3--
My message:
> add readme md in the scripts folders to example the process - first add strings in the text, then run `generate_pot_file` file than run update_po_files, then do_auto_translate. explain on software need to be installed (aider, gettextx
, more?)

--4--
Aider response:
To add a README.md file in the scripts folder explaining the process, we'll need to create a new file. Here's the file that needs to be created:

scripts\README.md

I'll wait for your approval to add this file to the chat before proceeding with the content.

Tokens: 11k sent, 10k cache write, 64 received. Cost: $0.04 message, $5.59 session.
Add README.md to the chat? (Y)es/(N)o [Yes]: n

--5--
The problem - the LLM understood correctly that I want to create scripts\README.md but aider offered me to add existing README.md to the chat, and not to create the new one

--6--
When I select "No" for adding the existing file, aider run ended.
When I created an empty README.md inside scripts folder and added it to the context, the same request worked without any problem

### Version and model info

Aider 0.57.0
Main model: claude-3-5-sonnet-20240620 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307

using --no-stream switch as well

**Comment by fry69** [comment]
Thank you for filing this issue.

This document may be helpful -> https://aider.chat/docs/usage/tips.html#creating-new-files

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
