### ISSUE TITLE
⭐ Feature request : Support project stack migration ( Angular => React, C => Java, ...)

### ISSUE THREAD

**Issue by Erim32** [Aider-AI/aider#1745]
### Issue

It would be great to have a feature that helps migrate an old project to a new technical stack, adapting code and file paths

**Comment by fry69** [comment]
Thank you for filing this issue.

I do not think aider can help with this out of the box.

But I think a place (other than Discord) where aider users and enthusiasts can share commonly uses prompts and workflows would be a good idea. An example would be how to do mentioned stack migrations.

Also note that you can script aider (to some extent) and this way build up workflows which could do migrations/conversions. See here -> https://aider.chat/docs/scripting.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
