### ISSUE TITLE
Aider not support Azure AD token provider

### ISSUE THREAD

**Issue by wissne** [Aider-AI/aider#1755]
LiteLLM is capable of supporting AD token, whereas Aider is not. May we add the aforementioned feature? The following is the code snippet:

```python
from litellm import completion
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
token_provider = get_bearer_token_provider(DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default")
response = completion(
    model = "azure/<your deployment name>",             # model = azure/<your deployment name>
    api_base = "",                                      # azure api base
    api_version = "",                                   # azure api version
    azure_ad_token_provider=token_provider,
    messages = [{"role": "user", "content": "good morning"}])
```

**Comment by fry69** [comment]
Related #1653

**Comment by bakes82** [comment]
It should also be able to support the service principal variables
https://learn.microsoft.com/en-us/python/api/overview/azure/identity-readme?view=azure-python#service-principal-with-secret

@paul-gauthier - This is definitely needed for us Azure OpenAI Enterprise users, we dont have the option to use the api keys, and the method of passing in the token is cumbersome and the token then expires and you need to relaunch the program.

**Comment by fry69** [comment]
Shouldn't this be handled by LiteLLM?

**Comment by bakes82** [comment]
> Shouldn't this be handled by LiteLLM?

LiteLLM already supports it.... We need Aider to have an auth option for it.

**Comment by paul-gauthier** [comment]
You can add a `extra_params` dict to model settings to pass anything you like to litellm's completion() call.

https://aider.chat/docs/config/adv-model-settings.html#model-settings

**Comment by bakes82** [comment]
> ```python
> token_provider = get_bearer_token_provider(DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default")
> ```
Thats not the ask, the ask is how do we set the token provider as illustrated above
token_provider = get_bearer_token_provider(DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default")

**Comment by fry69** [comment]
This seems to be a special use case. How about setting up a LiteLLM proxy which handles all this?

**Comment by bakes82** [comment]
@fry69 
Actually its the best practice for using Azure Open AI or any azure service, so you saying its "special" just means youre not an azure developer, especially when you get into the volume we use it and have to load balance requests across multiple data centers in azure, nor would you ever expose out master api keys to hundreds of developers....

@wissne for the proxy this is what my config looks like:

```yaml
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: https://apiminstance.azure-api.net
      tenant_id: 1234
      client_id: 1234
      client_secret: shhhh
      api_version: "2024-06-01"
      extra_headers:
        User-Name: Name
```

In the .env I set these:
```
AZURE_AD_TOKEN=test // You need to set a token or api key or aider errors
AZURE_API_BASE=http://localhost:4000
```

python -m aider --model azure/gpt-4o

**Comment by fry69** [comment]
@bakes82 

> Actually its the best practice for using Azure Open AI or any azure service, so you saying its "special" just means youre not an azure developer, especially when you get into the volume we use it and have to load balance requests across multiple data centers in azure, nor would you ever expose out master api keys to hundreds of developers....

That is a special enterprise use case for me, which aider should not be concerned about. aider uses LiteLLM to abstract from this, and if LiteLLM cannot handle this on its own (or via its proxy service, which seems to work for you), I'd start question its purpose.

**Comment by ishaan-jaff** [comment]
You can do this with the LiteLLM python SDK: https://docs.litellm.ai/docs/providers/azure#azure-ad-token-refresh---defaultazurecredential - there's no need to use the proxy server for this @bakes82 @fry69

**Comment by fry69** [comment]
>  there's no need to use the proxy server for this

If you want aider to work in this setup you currently have to use the proxy.

**Comment by bakes82** [comment]
> special enterprise use case for me

Odd most people seem to want to target multi billion dollar enterprises that have hundreds of developers.

Why even support any auth in the program? Just have the proxy do it all, or better yet, why not just let us pass in a proxy config and aider can start it and/or pull all the auth info from that instead.

**Comment by fry69** [comment]
> > special enterprise use case for me
> 
> Odd most people seem to want to target multi billion dollar enterprises that have hundreds of developers.

If $enterprise thinks this is so important, $enterprise can send a $developer to implement this for them.

> Why even support any auth in the program? Just have the proxy do it all, or better yet, why not just let us pass in a proxy config and aider can start it and/or pull all the auth info from that instead.

This is a not-for-profit open source tool (as far as I know), these authentication methods benefit all who can use openly accessible LLM endpoints, a huge amount hobbyists, free lance developers and probably a few employed ones.

But if you ask so, I'd love to outsource everything to LiteLLM proxy and not having to deal with a gazillion of command line options and environment variables.

**Comment by paul-gauthier** [comment]
@ishaan-jaff does litellm provide a way to trigger this token refresh through environment variable configuration or by passing a simple parameter to the completion call? By simple, I mean something that the user can specify in a yaml config file -- not via running python code.

**Comment by WGlenn43** [comment]
> > there's no need to use the proxy server for this
> 
> If you want aider to work in this setup you currently have to use the proxy.

Is there documentation on how to setup the proxy? Azure seems to be disabling direct API keys for certain amount of usage so now I'm required to figure this out
