### ISSUE TITLE
Adding directories doesn't ignore __pycache__ etc.

### ISSUE THREAD

**Issue by dokterbob** [Aider-AI/aider#1779]
### Issue

When adding directories of Python code, things like __pycache__ should be ignored rather than added to context. They are not, creating confusion for the model and adding extraneous tokens.

### Version and model info

Aider: 0.57.1

**Comment by fry69** [comment]
Thank you for filing this issue.

aider's source of truth is the git repository. If Those directories do not get ignored via `.gitignore` they might get added. That is outside of the control of aider.

**Comment by dokterbob** [comment]
Thanks for the quick follow-up @fry69. 

They are most definitely not in the GIT repo. Is aider using home dir/system GIT ignores, like GIT does?

**Comment by fry69** [comment]
aider uses GitPython, which respects everything what git does too (except for some arcane features which do not matter for this discussion). Most certainly GitPython respects git ignore files everywhere where git expects those/are configured too look for.

It may be possible that aider cannot see those configuration files e.g. if it runs in a separate environment like Docker.

**Comment by dokterbob** [comment]
🤔 I did add a directory outside the GIT root (to make aider aware of types there), could that be the cause?

**Comment by fry69** [comment]
Yes. That is outside of the control of git and its ignore files. If you add a directory with e.g. `/read` it will recursively add the whole contents (that was a requested feature).

If that is a problem you have to add single files manually via `/read` not whole directories.

**Comment by fry69** [comment]
I'm closing this issue for now.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.

**Comment by swarmer** [comment]
This is a very normal scenario to add a folder of source files at once, in fact that must be why this functionality even exists. And basically every time there will be a __pycache__ folder there. There's clear room for improvement here, as it is passing a folder to /read will be useless a for a lot of users.

**Comment by paul-gauthier** [comment]
You can also use a glob like `foo/**/*.py`.
