### ISSUE TITLE
Paste problem when using --no-pretty

### ISSUE THREAD

**Issue by PierrunoYT** [Aider-AI/aider#1783]
### Issue

When you want to add multiple files add once to the chat or copy a multiline text and paste it in the terminal it just takes the first line and then it keeps going because every new line in the copied text will be placed as a new prompt

**Comment by PierrunoYT** [comment]
https://github.com/paul-gauthier/aider/issues/1697

**Comment by PierrunoYT** [comment]
This issue does not happen without no pretty

**Comment by fry69** [comment]
> This issue does not happen without no pretty

Yes, that is intentional. With `--pretty` (the default) prompt toolkit gets used which can handle multi-line pastes. With `--no-pretty` a basic console gets used, which cannot handle these multi-line pastes.

Please use `/clipboard` when using `--no-pretty` to add multi-line text to the context.

**Comment by PierrunoYT** [comment]
> > This issue does not happen without no pretty
> 
> Yes, that is intentional. With `--pretty` (the default) prompt toolkit gets used which can handle multi-line pastes. With `--no-pretty` a basic console gets used, which cannot handle these multi-line pastes.
> 
> Please use `/clipboard` when using `--no-pretty` to add multi-line text to the context.

Okay thx you but I would I add multiple files add once? I always did /add and then the path of the files.

**Comment by fry69** [comment]
> Okay thx you but I would I add multiple files add once? I always did /add and then the path of the files.

This should work fine as long as your paste does not contain newlines. E.g. if you copy this and paste it in aider after typing `/add` + `space` there it should work just fine, even if you use `--no-pretty`:
```
file1 src/file2 data/file3
```

**Comment by fry69** [comment]
FYI: `/clipboard` just got renamed to a much shorter and better named `/paste` -> https://github.com/paul-gauthier/aider/commit/c2c4dbd2a8319f3eab72939f60e2b199a452ff1d

**Comment by fry69** [comment]
I'm closing this issue for now.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.

**Comment by PierrunoYT** [comment]
I think this got fixed somehow
