### ISSUE TITLE
I get answers in Spanish (Aider 0.2.5 and o1-mini)

### ISSUE THREAD

**Issue by younes-io** [Aider-AI/aider#1791]
### Issue
I get answers in Spanish, which is weird. I don't doubt the model because I use it in other tools, and I get answers in English, but with Aider **~~0.2.5~~** 0.57.1 I get this behavior
(my use case requires o1-mini, so testing or working with other models is worthless. I need o1-mini)

### Version and model info
aider 0.57.1
model: o1-mini

**Comment by fry69** [comment]
Thank you for filing this issue.

This is a quirk of this model (and some others) when there not enough content in the context. If you keep seeing this behavior even with some files in the context and some chat history, try using a code conventions file and put "Always answer in English" into it.

See here -> https://aider.chat/docs/usage/conventions.html

**Comment by younes-io** [comment]
Thank you for the feedback. 

The 0.2.5 was a typo.

I always start the chat by adding all the source files (around 12k tokens). The source code uses English in comments and variable naming conventions, etc. Also, I find it hard to blame the model; I use it in other contexts (not using aider), and I have never experienced this hallucination.

**Comment by jorgecolonconsulting** [comment]
@younes-io check if this fixes your problem: https://github.com/paul-gauthier/aider/issues/1850#issuecomment-2392342219

https://github.com/paul-gauthier/aider/pull/1907

**Comment by younes-io** [comment]
@jorgecolonconsulting I think it would; it's similar to my workaround: I added a `CONVENTIONS.md` file with a prompt requesting the model always to use English (as suggested by @fry69 )
Any idea when your fix will be merged? Btw, I'll test later and let you know if I notice any hallucinations. Thank you

**Comment by fry69** [comment]
> Any idea when your fix will be merged?

Only @paul-gauthier knows.

**Comment by AspireOne** [comment]
@younes-io Not sure if I'm missing something or why no one mentioned it, but this problem already popped up multiple times recently - aider send info about your system to the LLM, including the system language. For me, it included a simple "System language: cs", and it made aider sometimes reply in czech. Soon after raising the issue, a "chat-language" flag was added. I have it in my .aider.conf.yml as "chat-language: "en"" and had no issues since. You can try it.

**Comment by younes-io** [comment]
@AspireOne Oh I didn't know that. I will definitely try this! Thank you!

**Comment by younes-io** [comment]
> @younes-io Not sure why no one mentioned it, but this problem already popped up multiple times recently - aider sends info about your system to the LLM, including system language. For me, it included a simple "System language: cs", which was enough to sometimes cause aider to reply in czech. Soon after raising the issue, a `chat-language` flag was added. I have it in my .aider.conf.yml as `chat-language: "en"` and had no issues since. You can try it. Might also be able to pass it using `--chat-language`

I tried this.. for now, I didnt see any issues.. I will consider this solved :)

**Comment by matr1xp** [comment]
I got the same issue now as suddenly aider responses were in Spanish. 
Passing `--chat-language en` works but why does it suddenly default to Spanish???

**Comment by paul-gauthier** [comment]
This doc may be helpful:

 https://aider.chat/docs/faq.html#why-is-the-llm-speaking-to-me-in-an-unexpected-language
