### ISSUE TITLE
keep existing code...

### ISSUE THREAD

**Issue by trashhalo** [Aider-AI/aider#1832]
### Issue

been having trouble with sonnet 3.5 doing edits to files where they remove everything and replace the implementation with `# ... (keep existing code)` some new function then ` # ... (keep existing code)` it doesnt seem to understand that the search and replace logic cannot do that. unfortunatly the search and replace is correctly formed and so the file is commited totally gutted

### Version and model info

running main line. O1 preview gpt4o architect

**Comment by trashhalo** [comment]
I've been running in the new architect mode and I actually think it's related to this. Architect will often reply and pseudo code like this with these comments and when the editor sees that it carries it forward replacing the whole file with just a version that has only what the architect had and the comments. It doesn't happen every time just calling out that the editor might need some prompt tweaks

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by trashhalo** [comment]
Thanks for the link! Very helpful. One thing I wanted to note is the search and replace block applied correctly. So it wasn't an issue with it not following the format. It seems like the doc was mostly focused on that.

This was the case where the architect described a change that included comments as instructions. Like pseudo code. and the editor model said okay and replaced the file with the one new functions and two comments saying put the rest of the code here, like the architect described.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
