### ISSUE TITLE
Wrapping third-party API errors

### ISSUE THREAD

**Issue by golergka** [Aider-AI/aider#1833]
### Issue

When I hit a third-party API error, for example this Antropic rate limit, I'm hit with this:

```
Retrying in 1.0 seconds...
litellm.RateLimitError: AnthropicException -
b'{"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has
exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the
response headers for current usage. Please reduce the prompt length or the maximum tokens
requested, or try again later. You may also contact sales at
https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}'
```

What if, instead, Aider processed this error and presented an interface to the user, with abort/retry/wait choice?

### Version and model info

Aider v0.58.0
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 21 files
Repo-map: using 1024 tokens, auto refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

FYI, aider already retries over and over again for 1min before finally giving up.

LLM APIs can return a huge number of weird errors. It would be pretty tough to parse them all. But I am interested in making this sort of thing prettier, yes.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
