### ISSUE TITLE
Uncaught FileNotFoundError in posixpath.py line 384

### ISSUE THREAD

**Issue by DeusExMachina-Agents-LLM** [Aider-AI/aider#1845]
Aider version: 0.58.1
Python version: 3.10.12
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 5.15.153.1-microsoft-standard-WSL2 (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 350, in main
    default_config_files = [conf_fname.resolve()]  # CWD
  File "pathlib.py", line 1077, in resolve
    s = self._accessor.realpath(self, strict=strict)
  File "posixpath.py", line 397, in realpath
    return abspath(path)
  File "posixpath.py", line 384, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by fry69** [comment]
Thank you for filing this issue.

It is unclear what caused this Exception, but it should be handled more gracefully, so I labeled it a bug for now.

**Comment by DnAp** [comment]
Same problem, restarting terminal solved the problem

Aider version: 0.59.1
Python version: 3.10.12
Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 5.15.153.1-microsoft-standard-WSL2 (64bit)
Git version: git version 2.34.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
