### ISSUE TITLE
developing Aider using Aider?

### ISSUE THREAD

**Issue by lockmeister** [Aider-AI/aider#1872]
### Issue

I cloned aider and made some edits locally. I used aider itself to assist (installed globally using pipx to avoid conflicts).
I ran my local branch [as per the instructions](https://github.com/paul-gauthier/aider/blob/main/CONTRIBUTING.md) using `pip install -e .` , in a local virtual environment (I use venv).
There seemed to be an issue with the repo map, as I switched between test driving my local version of aider, and using the global aider to code. 

My next thing to try is to create a dedicated folder outside the development repo to safely use the local aider and test it.
Set up a virtual environment in that folder and install the development version via `pip install -e path-to-development-repo`

Can anyone suggest a better workflow to avoid this issue while working on aider? Any other tips for developing aider?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, what is "this issue" that you're trying to avoid. I develop aider and run it with a `pip install -e .` approach.
