### ISSUE TITLE
Suggestion: Partial search fragments

### ISSUE THREAD

**Issue by boosh** [Aider-AI/aider#1886]
### Issue

I sometimes get aider to work on entire files, e.g. to add docstrings, type hints, etc.

It's annoying when I send a file that's several hundred lines long, only for it to send it all back to me as the search string. It'd be much better if it could elide the middle part. Perhaps using tags as in #1803 would make this possible. 

E.g. tell it "If the search text will be more than 10 lines, elide it and only include the first and last 5 lines". 

We could tell it to include the start search block in `<aiderSearchStart>` tags and the end in `<aiderSearchEnd>` tags, then just select everything in between with a regex.

This'd make working with aider faster and cheaper.

### Version and model info

Aider: 0.58.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I've tried this without much success. But happy to see some benchmark results that indicate it has become viable with the latest models.

**Comment by boosh** [comment]
Shame. Thanks for trying.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
