### ISSUE TITLE
Error with Aider when working with IBM Granite 8B Code Instruct model - “No file name provided before ‘’’ in file listing”

### ISSUE THREAD

**Issue by sunbox001** [Aider-AI/aider#1899]
### Issue

I’m encountering an issue when using Aider with the IBM Granite 8B Code Instruct model. The tool throws the following error:

No file name provided before ''' in file listing. The LLM did not conform to the edit format.

Environment:

	•	IBM Granite 8B Code Instruct model
	•	Aider version: 0.56.0
	•	System: Windows 11

### Version and model info

Aider 0.56.0

**Comment by fry69** [comment]
Thank you for filing this issue.

This document may be helpful -> https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by sunbox001** [comment]
> Thank you for filing this issue.
> 
> 
> 
> This document may be helpful -> https://aider.chat/docs/troubleshooting/edit-errors.html

Tried all options given in the document but still facing same error. Seems granite is not giving file name for creation.

**Comment by fry69** [comment]
Some LLMs may not be capable of understanding aider's system prompts or be unable to reply in the correct format. An 8B model falls likely in this category.

See also -> https://aider.chat/docs/leaderboards/

**Comment by paul-gauthier** [comment]
Yes, an 8B model is probably not capable of working well with aider.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
