### ISSUE TITLE
Support for Internal GENAI APIs Without Proxy for Aider Compatibility

### ISSUE THREAD

**Issue by sunbox001** [Aider-AI/aider#1900]
### Issue

We are currently working with internal GENAI APIs, which are not directly compatible with OpenAI or other models. To make Aider work with these APIs, we have to use a proxy to bridge the compatibility gap.

Question:
Is there a better or more streamlined way to connect Aider to our internal GENAI APIs without needing a proxy? Are there any plans to support custom or internal API configurations that aren’t directly compatible with OpenAI models?

### Version and model info

Aider :0.56.0

**Comment by fry69** [comment]
Thank you for filing this issue.

Currently there are no plans to use other methods than those provided via LiteLLM (-> https://github.com/BerriAI/litellm) to communicate with LLM endpoints as far as I know.

**Comment by paul-gauthier** [comment]
Aider can work with hundreds of providers via litellm. You'll need to use a proxy if your internal API isn't compatible with any of them.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
