### ISSUE TITLE
aider sonnet 3.5, whole format

### ISSUE THREAD

**Issue by sprappcom** [Aider-AI/aider#1915]
### Issue

the rest of the file is deleted / removed. should i use whole or diff format doing rustlang?

use crate::templates::ArticleTemplate;

// ... rest of the file content ...

### Version and model info

latest aider of today
ubuntu 24.04

**Comment by fry69** [comment]
Thank you for filing this issue.

aider defaults to `diff` for a reason. LLMs tend to shorten their output this way as they are not trained/do not expect to be used as a code editing tool. In doubt, trust aider's defaults.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/edit-errors.html

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
