### ISSUE TITLE
remove litellm dependency

### ISSUE THREAD

**Issue by pseudotensor** [Aider-AI/aider#1926]
### Issue

litellm is a massive project with many constraints that leave aider behind in capability and use.

For example, right now aider requires `tokenizers==0.19.1` for litellm, even if litellm itself requires even older version

https://github.com/BerriAI/litellm/blob/main/requirements.txt#L40

It's very overconstrained.

In many cases, most endpoints are OpenAI compatible (groq, vLLM, together.ai, etc. etc.) so at least I'd hope we can make litellm optional and at least support base OpenAI as independent option.

Issue is right now I can't use latest transformers with llama 3.2 support while also using aider.

### Version and model info

latest all as of right now.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/install/pipx.html

**Comment by pseudotensor** [comment]
I see, I'm on Ubuntu 22.04 and our images typically are on Wolfi for security reasons.

**Comment by nickandbro** [comment]
@pseudotensor Do you mind please sharing your wolfi Dockerfiles?
