### ISSUE TITLE
Error when using o1 architect with sonnet editor model

### ISSUE THREAD

**Issue by transcendr** [Aider-AI/aider#1942]
### Issue

Not sure what I'm doing wrong here.  Is there a way to do this?

Tried `aider --o1-mini --architect --editor-model sonnet`

The architect part works but when I press y to edit the suggest files, I get:

![image](https://github.com/user-attachments/assets/a8ea7c86-f5bb-4128-a93d-fa8c29cf0f33)

### Version and model info

![image](https://github.com/user-attachments/assets/8ba91c0f-3d99-4348-a816-dea0519180e5)

**Comment by fry69** [comment]
Thank you for filing this issue.

`sonnet` is a shorthand that works only as a command line argument (`--sonnet`), you need to specify the full model name for the editor model, e.g. `anthropic/claude-3-5-sonnet-20240620`

Correct command line is:
```
aider --o1-mini --architect --editor-model anthropic/claude-3-5-sonnet-20240620
```

**Comment by transcendr** [comment]
haha i feel dumb :) thanks

**Comment by fry69** [comment]
As this issue appears to be resolved, I'm closing it.

If any new related concerns arise, please feel free to comment, and I'll reopen the issue.
