### ISSUE TITLE
Which deepseek model to use?

### ISSUE THREAD

**Issue by lgandecki** [Aider-AI/aider#1952]
### Issue

this page https://aider.chat/2024/09/26/architect.html
suggests the best combination is o1-preview + deepseek, but there is no instruction how to use it, when I try:

aider --model o1-preview --architect --editor-model deepseek --editor-edit-format whole server.ts

it asks:

Did you mean one of these?
- deepseek-chat
- deepseek-coder
- deepseek/deepseek-chat
- deepseek/deepseek-coder

so should I use deepseek-chat? or coder? and are those the new 2.5 versions?

I'm doing:
aider --model o1-preview --architect --editor-model deepseek/deepseek-coder --editor-edit-format whole server.ts

which says:

Main model: o1-preview with architect edit format
Editor model: deepseek/deepseek-coder with whole edit format

but I feel uneasy that I might be using an old and/or wrong deepseek model.

Thanks for any suggestions!

**Comment by lgandecki** [comment]
to answer myself, and for a lost googlers out there, looks like those two models is actually one and the same:

"The DeepSeek V2 Chat and DeepSeek Coder V2 models have been merged and upgraded into the new model, DeepSeek V2.5. The new model significantly surpasses the previous versions in both general capabilities and code abilities. For backward compatibility, API users can access the new model through either deepseek-coder or deepseek-chat"

from https://platform.deepseek.com/api-docs/

**Comment by Yona544** [comment]
```
Did you mean one of these?

deepseek-chat
deepseek-coder
deepseek/deepseek-chat
deepseek/deepseek-coder
```

It asks "what do I mean" but I don't have the option to respond

**Comment by lgandecki** [comment]
I just restarted it picking one of those. Funny thing is, as far as I know they are all the same model, to make it a bit more confusing 😂
