### ISSUE TITLE
Discord link broken

### ISSUE THREAD

**Issue by johhansantana** [Aider-AI/aider#1960]
### Issue

I'm trying to join discord via the discord button in aider.chat but seems to take you to a broken invite.

**Comment by fry69** [comment]
Thank you for filing this issue.

> I'm trying to join discord via the discord button in aider.chat but seems to take you to a broken invite.

This Discord link on the bottom of the left sidebar works for me. Which Discord link exactly does not work for you?

**Comment by johhansantana** [comment]
it's this one:

https://discord.com/invite/Tv2uQnR88V

![CleanShot 2024-10-08 at 17 50 15](https://github.com/user-attachments/assets/c580cc4c-ef4f-440d-9995-bb5461873f05)

**Comment by fry69** [comment]
That one works for me and is the same invite link as everywhere.

Can you please try with a different browser or machine (mostly to ensure you have a clean environment, no plugins/logins that could interfere)?

**Comment by johhansantana** [comment]
I'm a noob on discord. I opened the link in cognito and it worked but I had to create a new account so I closed that and opened my discord app and pasted the invite link and that worked! 

Sorry.
