### ISSUE TITLE
Uncaught TypeError in main.py line 189

### ISSUE THREAD

**Issue by 2themaxx** [Aider-AI/aider#1969]
Aider version: <module 'aider.__version__' from 'C:\\Users\\jai_m\\.pixi\\envs\\aider\\Lib\\site-packages\\aider\\__version__.py'>
Python version: 3.12.7
Platform: Windows-11-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 11 (64bit)
Git version: git version 2.24.0.windows.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "__main__.py", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 470, in main
    launch_gui(argv)
  File "main.py", line 189, in launch_gui
    if "-dev" in __version__:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'module' is not iterable

```

**Comment by 2themaxx** [comment]
I'm installing using pixi from prefix-dev

pixi init
pixi install --pypi aider-chat[browser]
pixi add python
pixi run aider 

Even though your virtual environment detection doesn't see it, you can see the path to the .pixi environment.

**Comment by fry69** [comment]
If you want aider to work well currently, please use `pipx` to install it (recommended) or another support method, see here ->

https://aider.chat/docs/install/install.html
