### ISSUE TITLE
/clipboard not working

### ISSUE THREAD

**Issue by scho-to** [Aider-AI/aider#1989]
Hi, the command /clipboard is not working in aider:

![image](https://github.com/user-attachments/assets/c7f4716c-639f-4e7f-9adf-92a0eacc8145)

Aider version: 0.59.1
Python version: 3.12.5
Platform: Linux-6.11.0-102007-tuxedo-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.11.0-102007-tuxedo (64bit)
Git version: git version 2.34.1

Aider v0.59.1
Main model: openrouter/anthropic/claude-3.5-sonnet with architect edit format, prompt cache, infinite output
Editor model: openrouter/anthropic/claude-3.5-sonnet with editor-diff edit format
Weak model: openrouter/anthropic/claude-3-haiku-20240307
Git repo: .git with 11 files
Repo-map: using 1024 tokens, files refresh

**Comment by fry69** [comment]
Thank you for filing this issue.

`/clipboard` was renamed to `/paste` in `0.58.0`, see here -> https://aider.chat/HISTORY.html#aider-v0580

**Comment by scho-to** [comment]
Hey @fry69, I just noticed in the release history :+1: . But the documentation still says /clipboard on [this page](https://aider.chat/docs/usage/commands.html#entering-multi-line-chat-messages).  

You might update this to avoid confusion.

Also /help command adviced me with this command:
prompt: 
`/help How can I paste content from my clipboard? `
Answer:
`To paste content from your clipboard in aider, you can use the /clipboard command. This command allows you to directly paste text from your clipboard into the chat. Here's how you   
can use it:                                                                                                                                                                           

 1 Copy the content you want to paste to your clipboard.                                                                                                                              
 2 In the aider chat, type /clipboard and press Enter.                                                                                                                                
 3 The content from your clipboard will be pasted into the chat.                                                                                                                      

This feature is particularly useful for sharing longer pieces of text or code snippets without having to manually type them out.                                                      

Here are some relevant documentation links that you might find helpful:                                                                                                               

 • https://aider.chat/docs/usage.html                                                                                                                                                 
 • https://aider.chat/docs/tips.html                                                                                                                                                  

Remember that you can also use other methods to input multi-line messages in aider, such as:                                                                                          

 • Pasting a multi-line message directly into the chat.                                                                                                                               
 • Using { at the start and } at the end of a multi-line message.                                                                                                                     
 • Using Meta-ENTER (or Esc+ENTER in some environments) to start a new line without sending the message.                                                                              

These methods can be useful depending on your specific needs and the content you're trying to share.`

**Comment by fry69** [comment]
Fixed.
