### ISSUE TITLE
Uncaught KeyError in models.py line 997

### ISSUE THREAD

**Issue by cmayers** [Aider-AI/aider#1994]
Aider version: 0.59.1
Python version: 3.10.12
Platform: Linux-5.15.0-122-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 5.15.0-122-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 582, in main
    problem = models.sanity_check_models(io, main_model)
  File "models.py", line 933, in sanity_check_models
    problem_main = sanity_check_model(io, main_model)
  File "models.py", line 977, in sanity_check_model
    possible_matches = fuzzy_match_models(model.name)
  File "models.py", line 997, in fuzzy_match_models
    provider = (attrs["litellm_provider"] + "/").lower()
KeyError: 'litellm_provider'

```

**Comment by fry69** [comment]
Thank you for filing this issue.

Can you please post the command line or the announcement lines when you start aider?

**Comment by cmayers** [comment]
> Thank you for filing this issue.
> 
> Can you please post the command line or the announcement lines when you start aider?

aider --model ollama/qwen2.5 .
and
aider --model ollama/llama3.2:3b-instruct-fp16 .

**Comment by fry69** [comment]
I cannot reproduce this problem locally.

Can you please try to install or reinstall aider in a separate Python environment? Either with `venv` or `pipx`?

Please remove the existing environment/aider installation first, e.g. with `pipx`:
```shell
$ pipx uninstall aider-chat
uninstalled aider-chat! ✨ 🌟 ✨
```
```shell
$ pipx install aider-chat
  installed package aider-chat 0.59.1, installed using Python 3.12.7
  These apps are now globally available
    - aider
done! ✨ 🌟 ✨
```

**Comment by paul-gauthier** [comment]
Did you make a custom model settings json file?

**Comment by cmayers** [comment]
If I issue aider --model ollama/qwen2.5-coder . 
it start fine

**Comment by cmayers** [comment]
> Did you make a custom model settings json file?

Yes I did. But for only one model and the included model is not presenting an error. I will try including the models which gave the error in the model settings json file. I wll report back the behavior.

**Comment by cmayers** [comment]
> > Did you make a custom model settings json file?
> 
> Yes I did. But for only one model and the included model is not presenting an error. I will try including the models which gave the error in the model settings json file. I wll report back the behavior.

Confirmed. As soon as I included the model's parameters into the model settings json the error no longer shows.

Thanks!
