### ISSUE TITLE
Automatically add suggested files and proceed?

### ISSUE THREAD

**Issue by mr-september** [Aider-AI/aider#2014]
### Issue

Using older versions a few months ago, Aider would automatically add files it suggested to the chat, and go on to edit them, which was convenient.

Now I can't seem to trigger that anymore. Was this unintended behaviour that was fixed? Is there any option to re-enable it, and/or a shortcut command to add all the files aider just suggested?

### Version and model info

Aider v0.59.1
Model: deepseek/deepseek-coder with diff edit format, prompt cache, infinite output
Git repo: .git with 740 files
Repo-map: using 1024 tokens, auto refresh
Command Line Args:   --model deepseek/deepseek-coder

**Comment by fry69** [comment]
Thank you for filing this issue.

You can use `--yes-always` to automatically answer yes to these questions (but not to possibly destructive questions), see here -> https://aider.chat/docs/config/options.html#--yes-always

**Comment by fry69** [comment]
Correct. For security reasons aider will not execute shell commands received from the LLM automatically.
