### ISSUE TITLE
Uncaught AttributeError in main.py line 134

### ISSUE THREAD

**Issue by amritloksom** [Aider-AI/aider#2028]
Aider version: 0.59.1
Python version: 3.12.7
Platform: macOS-15.0.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.0.0 (64bit)
Git version: git version 2.46.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 532, in main
    check_gitignore(git_root, io)
  File "main.py", line 134, in check_gitignore
    if repo.ignored(".aider"):
       ^^^^^^^^^^^^
AttributeError: 'Repo' object has no attribute 'ignored'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
