### ISSUE TITLE
run a prompt from a file.

### ISSUE THREAD

**Issue by AsadJobanputra1** [Aider-AI/aider#2033]
i'd like to be able to store a large prompt in an md file that explains a project and what the codestructure is etc.  i'd like the /code extension to execute based on the contents of the .md file.

**Comment by 5ocworkshop** [comment]
In what way are you not able to to do this today?  Could you not just put the prompt in a file and load it?

**Comment by AsadJobanputra1** [comment]
i figured it out with some help from the community, the feature i was
looking for was aider --message-file <long prompt instructions template.md'
Best Regards,

Asad
416-230-4207
Book a Meeting <https://calendly.com/asad-jobanputra>

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
