### ISSUE TITLE
/help docs are missing url

### ISSUE THREAD

**Issue by mark-os** [Aider-AI/aider#2040]
### Issue

Looking at the `.aider.chat.history.md` I found that all the relevant docs provided to the LLM do not contain URL's, but that is not correct, the `help.py` file shows the metadata should contain url for each vector but it's actually blank:
```
// tail of docstore.json
3a-4446-8d65-6778f534f366", "92ae0bda-5a6b-41cc-8d5a-c399a1f7a474"], "metadata": {"filename": "index.md", "extension": ".md", "url": ""}}, "f2a7307a-8e88-4064-92f7-6b220f9f1dd4": {"node_ids": ["7a715684-a67a-445a-84e8-85a5420fbf99", "e6b59240-de7a-4573-9197-c41822ac1809", "7e9c8bbb-b3d4-4f46-b913-6647a7453bfa", "061b7aa9-0661-497b-8403-f9f4e3be8a19"], "metadata": {"filename": "index.md", "extension": ".md", "url": ""}}}}
```

### Version and model info

aider 0.59.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
