### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by CraftsMan-Labs** [Aider-AI/aider#2048]
Aider version: 0.57.1
Python version: 3.11.9
Platform: Windows-10-10.0.22631-SP0
Python implementation: CPython
Virtual environment: No
OS: Windows 10 (64bit)
Git version: git version 2.46.1.windows.1

Aider v0.57.1
Model: deepseek/deepseek-coder with diff edit format, prompt cache, infinite output
Git repo: .git with 55 files
Repo-map: using 1024 tokens, auto refresh
Added src\chat_system\README.md to the chat.
Added src\chat_system\step_processor.py to the chat.
Restored previous conversation history.

![image](https://github.com/user-attachments/assets/2c11b94b-1436-405a-ba41-7b361a31680f)
 Text formatting is not implemented properly and changes are not implemented as well

**Comment by paul-gauthier** [comment]
This should be fixed in the latest version. You can get it like this:

```
aider --upgrade

# or...

python -m pip install --upgrade aider-chat
```

If you have a chance to try it, let me know if it works better for you.
