### ISSUE TITLE
OpenAI o1 support?

### ISSUE THREAD

**Issue by robd003** [Aider-AI/aider#2064]
### Issue

Just wondering if OpenAI o1 support is on the roadmap

**Comment by paul-gauthier** [comment]
Yes it is supported.

**Comment by golergka** [comment]
Now that o1 is released without -preview suffix, may be there's point in re-opening this ticket?

**Comment by paul-gauthier** [comment]
There's no API access for `o1`. Any o1 models with API access are already supported.
