### ISSUE TITLE
Error: 429 Too Many Requests

### ISSUE THREAD

**Issue by 00010110** [Aider-AI/aider#2108]
### Issue

To use bedrock model,Error: 429 Too Many Requests
![image](https://github.com/user-attachments/assets/ee95d967-3fdd-45a4-ae22-d2070c893376)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It looks like AWS is saying you have exceeded your rate limit.

**Comment by 00010110** [comment]
it can be consistently reproduced. When I ask twice in a row, the first time returns normally, but the second time shows a rate limit warning.
