### ISSUE TITLE
Livecoding demo of using aider on itself

### ISSUE THREAD

**Issue by shihabdider** [Aider-AI/aider#2118]
### Issue

I assume that `aider` is being used to develop `aider` itself. I would love to see a livecoding stream of this (even if completely silent) to get a sense of how this tool is being used to develop a real application. A lot of what's available online is sparse and focused on tutorial level demos.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. I'm not sure I can make the time to record a live stream.

**Comment by paul-gauthier** [comment]
This video from the tutorials page does some non-trivial coding:

https://youtu.be/QlUt06XLbJE

**Comment by shihabdider** [comment]
> This video from the tutorials page does some non-trivial coding:
> 
> https://youtu.be/QlUt06XLbJE

OK this is pretty good.
