### ISSUE TITLE
Uncaught KeyError in models.py line 1039

### ISSUE THREAD

**Issue by lenohard** [Aider-AI/aider#2124]
Aider version: 0.60.0
Python version: 3.12.7
Platform: macOS-15.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.46.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 601, in main
    problem = models.sanity_check_models(io, main_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 975, in sanity_check_models
    problem_main = sanity_check_model(io, main_model)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 1019, in sanity_check_model
    possible_matches = fuzzy_match_models(model.name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "models.py", line 1039, in fuzzy_match_models
    provider = (attrs["litellm_provider"] + "/").lower()
                ~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'litellm_provider'

```

**Comment by lenohard** [comment]
I use a openai compatiable endpoint by settting the `OPENAI_API_BASE` and `OPENAI_API_KEY`. This service support anthropic's model, and I include the following settting in `~/.aider.model.settings.yml`: 
`- accepts_images: true
  cache_control: true
  caches_by_default: false
  edit_format: diff
  editor_edit_format: editor-diff
  editor_model_name: openai/claude-3-5-sonnet-20240620
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      anthropic-beta: prompt-caching-2024-07-31
  lazy: false
  name: openai/claude-3-5-sonnet-20240620
  reminder: user
  send_undo_reply: false
  streaming: true
  use_repo_map: true
  use_system_prompt: true
  use_temperature: true
  weak_model_name: openai/gpt-4o-mini
- accepts_images: true
  cache_control: true
  caches_by_default: false
  edit_format: diff
  editor_edit_format: editor-diff
  editor_model_name: openai/claude-3-5-sonnet-20241022
  examples_as_sys_msg: true
  extra_params:
    extra_headers:
      anthropic-beta: prompt-caching-2024-07-31
  lazy: false
  name: openai/claude-3-5-sonnet-20241022
  reminder: user
  send_undo_reply: false
  streaming: true
  use_repo_map: true
  use_system_prompt: true
  use_temperature: true
  weak_model_name: openai/gpt-4o-mini
- accepts_images: false
  cache_control: false
  caches_by_default: false
  edit_format: whole
  editor_edit_format: editor-diff
  editor_model_name: openai/gpt-4o
  examples_as_sys_msg: false
  extra_params: null
  lazy: false
  name: openai/o1-mini
  reminder: user
  send_undo_reply: false
  streaming: false
  use_repo_map: true
  use_system_prompt: false
  use_temperature: false
  weak_model_name: openai/gpt-4o-mini
- accepts_images: false
  cache_control: false
  caches_by_default: false
  edit_format: whole
  editor_edit_format: editor-diff
  editor_model_name: openai/gpt-4o
  examples_as_sys_msg: false
  extra_params: null
  lazy: false
  name: openai/o1-mini
  reminder: user
  send_undo_reply: false
  streaming: false
  use_repo_map: true
  use_system_prompt: false
  use_temperature: false
  weak_model_name: openai/gpt-4o-mini
`
this error occur when I run `aider --model openai/claude-3-5-sonnet-20241022` (fine for claude-3-5-sonnet-20240620).  and when I run `/models XXX` in the interactive session. I suspect that the problem is my edit on the model parameters file. but I don't know how? any insight? thanks.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Are you using a custom `.aider.model.metadata.json` file? It looks like it is missing the identified key?

**Comment by lenohard** [comment]
After I add the custom models in .aider.model.metadata.json, it works as expected. Thanks. By the way I also found this  through the /help RAG in aider, it works great. This is really a wonderful and comfortable tool.
