### ISSUE TITLE
Feature request: Refresh / update / add locally modified files

### ISSUE THREAD

**Issue by gwd** [Aider-AI/aider#2128]
### Issue

For complicated changes, I often find that it makes the most sense to make a few simple changes on top of what `aider` has done, and then ask it to pick up from there, rather than trying to explain in words what I want to be done.  But then `aider`'s idea of the state of then file has diverged from mine. `/add file.ext` refuses to add the file again, since it's already been added; this probably makes sense to avoid duplication, but it seems like having a `/refresh file.ext` command to re-upload the new version of the file would make sense.  (Or maybe some sort of diff from the previous version that aider sent?)

If there's an appropriate command that I missed, please let me know!

### Version and model info

Aider v0.59.1
Main model: claude-3-5-sonnet-20240620 with diff edit format, infinite output
Git repo: .git with 220 files
auto-commit: false

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider always reads the latest copy of the files from the file system when sending them to the LLM.

**Comment by gwd** [comment]
You're right -- I thought it didn't because at some point it tried to edit something I'd already edited; that must have been an LLM quirk.  Thanks for the quick response, and sorry for the noise!
