### ISSUE TITLE
Installation page of website should mention the required Python versions

### ISSUE THREAD

**Issue by ath** [Aider-AI/aider#2133]
### Issue

The install page suggests:
`python -m pip install -U aider-chat`

If the user has only installed Python 3.13 on his Windows machine this will not work. So the user will try the detailled installation instructions where he finally learns that simply the install command needs to be different:
`python -m pip install -U --upgrade-strategy only-if-needed aider-chat`

This however still fails.
A hint that a different version is required would be useful. (As well as a version range specification.)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

I'm adding a note to the install page.
