### ISSUE TITLE
Deepseek-coder actually uses deepseek-chat?

### ISSUE THREAD

**Issue by kopecmaciej** [Aider-AI/aider#2135]
### Issue

So I've been using the deepseek model for a few days and wanted to check its usage, strange, but it shows that only `deepseek-chat` was used all the time 
![Screenshot_2024-10-24-11-13-01_4622](https://github.com/user-attachments/assets/8ef544ec-305d-4e83-a40f-74724d812bb2)
And this is the command I'm using for running aider
```
aider --deepseek
```
or 
```
aider --model deepseek/deepseek-coder
```
Wha't im getting is this
![Screenshot_2024-10-24-11-13-20_13159](https://github.com/user-attachments/assets/420dade6-b912-4bc9-94de-973dc3a458c9)
And even I've run test couple minutes ago, and also only `deepseek-chat` shows usage, am I missing something or this is really an issue?
Thanks!

### Version and model info

Aider v0.60.0

**Comment by chemcoder-2020** [comment]
Deepseek models have been merged: https://api-docs.deepseek.com/ and deepseek-coder and deepseek-chat are supposed to be the same.

**Comment by kopecmaciej** [comment]
Ah, thank you for your reply, I didn't know that this is how it works at the moment, their dashboard is a bit confusing, thank you for your reply.
