### ISSUE TITLE
Specify model name like "claude-sonnet-latest"

### ISSUE THREAD

**Issue by jubishop** [Aider-AI/aider#2147]
### Issue

I have these options in my config file to use o1-preview as my architect and claude-sonnet as my editor, 

o1-preview: true
architect: true
editor-model: claude-3-5-sonnet-20241022

this works, but it'd be great if I could say something like "claude-sonnet-latest" instead of that specific date version.  for example, it appears I can use the more generic model name "gpt-4o".  I'm guessing this is really just an artifact of how these api's work, but still it'd be nice if aider would abstract over that for me and let me just say somehow in my config "use the latest, whatever that may be".

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can use `anthropic/claude-3-5-sonnet-latest`.

**Comment by jubishop** [comment]
oh thanks!  I missed that.
