### ISSUE TITLE
/read does not work with images, only /add

### ISSUE THREAD

**Issue by jbellis** [Aider-AI/aider#2151]
### Issue

Claude could not see an image with /read but could see it when /add was used.

### Version and model info

Aider 0.60.1

**Comment by 5ocworkshop** [comment]
Out of curiosity, are you using caching?  Does caching support images?

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
