### ISSUE TITLE
Add option to disable external web scraping

### ISSUE THREAD

**Issue by dtharumia** [Aider-AI/aider#2187]
### Issue

First of all, great work with this project! We are running Aider non-interactively through a script and have enabled the setting to "always say yes to every confirmation". Similar to #1522, Aider is trying to automatically scrape URLs in its outputs. We would like to disable this feature in its entirety or potentially only allow it for certain hostnames. Could we block the `cmd_web` function [here](https://github.com/Aider-AI/aider/blob/main/aider/coders/base_coder.py#L785) behind a config setting or environment variable so that we can restrict this behaviour even when not requiring confirmations?

**Comment by ifokeev** [comment]
Same issue here, need this a lot

**Comment by ifokeev** [comment]
Workaround is just create a new class and remove the function:

```
class Coder2(Coder):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def preproc_user_input(self, inp):
        if not inp:
            return

        if self.commands.is_command(inp):
            return self.commands.run(inp)

        self.check_for_file_mentions(inp)

        return inp
 ```

**Comment by hyperknot** [comment]
This is quite bad at the moment. For example the following message triggers downloading playwright install!

```
implement bsky login using the following snippet

import { BskyAgent } from '@atproto/api'

const agent = new BskyAgent({
  service: 'https://bsky.social'
})
await agent.login({
  identifier: 'handle.example.com',
  password: 'hunter2'
})
```

This is the official snippet from the docs, the URL really shouldn't be scraped! Especially in programming related commands, those URLs are usually not even scrappable. Playwright should really not be installed, nor httpx should be used.

**Comment by hyperknot** [comment]
In my case, it might be related to yes-always: true
Which is good for every thing answer, except for this.

**Comment by nang-dev** [comment]
agree

**Comment by nang-dev** [comment]
Done! Tested and ready for review.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by adnoh** [comment]
so the parameter is "--no-detect-urls"
