### ISSUE TITLE
Uncaught TypeError in main.py line 197

### ISSUE THREAD

**Issue by whoabuddy** [Aider-AI/aider#2193]
## Description

I wanted to try out the new browser mode, currently running Linux Mint 20.3 based on Ubuntu, Aider version installed with miniconda.

## Error Message

Aider version: <module 'aider.__version__' from '/home/whoabuddy/Dev/ai/miniconda3/envs/aider/lib/python3.11/site-packages/aider/__version__.py'>
Python version: 3.11.10
Platform: Linux-6.0.12-76060012-generic-x86_64-with-glibc2.31
Python implementation: CPython
Virtual environment: No
OS: Linux 6.0.12-76060012-generic (64bit)
Git version: git version 2.47.0

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 489, in main
    launch_gui(argv)
  File "main.py", line 197, in launch_gui
    if "-dev" in __version__:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'module' is not iterable
```

## Second Error

I'm seeing this now too when I run aider normally:

```
Aider v<module 'aider.__version__' from 
'/home/whoabuddy/Dev/ai/miniconda3/envs/aider/lib/python3.11/site-packages/aider
/__version__.py'>
Main model: claude-3-5-sonnet-20241022 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 101 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd line args
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
