### ISSUE TITLE
[Q] Is it possible to use `aider --apply` with output from web frontends like chatgpt.com?

### ISSUE THREAD

**Issue by NightMachinery** [Aider-AI/aider#2203]
o1-preview is cheaper on the subscription on chatgpt.com, and in general, I like the flexibility of working with raw LLMs. But applying edits from the web frontend to local files is a PITA. I often tell the LLM to "Output the whole code", but this causes the web UI to crash if the code is long. I am wondering if I could add some formatting preamble to my chat requests, and then use `aider --apply` to apply the changes?

I use git, so after the change is applied, I'll be able to review the changes and accept/reject parts of them. But I need an easy way to apply the changes on long files in the first place.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, no. There's isn't a way to do this. But it's an interesting idea.

**Comment by 5ocworkshop** [comment]
Is Selenium an option?

**Comment by NightMachinery** [comment]
I doubt the cat-and-mouse-game of automating the web UI is worth it.

**Comment by paul-gauthier** [comment]
You might be able to do this with one of aider's "editor" edit formats, like this:

1. Chat with GPT or Claude via their web app. Give it your source files and ask for the changes you want.
2. Use the COPY function to copy the entire LLM reply.
 
<img width="760" alt="2024-11-04_10-26-32" src="https://github.com/user-attachments/assets/357fb5b5-f649-4acc-bd81-f2740534b29b">

3. Run aider with the file(s) that the LLM wants to change and with the `/paste` command:

```
$ aider --edit-format editor-diff --msg /paste hello.py
───────────────────────────────────────────────────────────────────────────────────────────────
Creating empty file hello.py
Aider v0.61.1.dev
Model: claude-3-5-sonnet-20241022 with editor-diff edit format, prompt cache, infinite output
Added hello.py to the chat.
Use /help <question> for help, run "aider --help" to see cmd line args

I'll add the "Hello, World!" program to hello.py using a SEARCH/REPLACE block:

hello.py


 <<<<<<< SEARCH
 =======
 print("Hello, World!")
 >>>>>>> REPLACE



Tokens: 1.6k sent, 43 received.
Cost: $0.0053 message, $0.0053 session. Use --no-stream for accurate caching costs.
Applied edit to hello.py
```

**Comment by paul-gauthier** [comment]
Actually, I just pushed some improvements. You can now just run:

```
aider --apply-clipboard-edits hello.py
```


The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by NightMachinery** [comment]
@paul-gauthier Thanks! ❤️ Can you explain what this flag does? Does it call another LLM?

Also, what prompts does aider use to make the LLMs output stuff in these `SEARCH/REPLACE` blocks?
