### ISSUE TITLE
[Q] Difference between /ask and /code mode in multiprocessing

### ISSUE THREAD

**Issue by EugeneChoi4** [Aider-AI/aider#2207]
### Issue

Hello, I am working on a project that utilizes Aider to launch multithreaded aider processes. Using the default `/code` mode has worked fine for us, but after trying to use `/ask` mode, we seem to get an error with the multiprocessing serialization. Would the ask mode contain any non-pickleable functions that could be causing this?

### Version and model info

Aider v0.60.0 Model: gpt-4o-mini/gpt-4o

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sorry, I can't think of any salient difference. It's just a different prompt. 

This is well outside the supported scope of scripting aider. It would be difficult for me to help debug.

**Comment by EugeneChoi4** [comment]
Could you possibly point me towards where in the code the the two prompts are functionally being treated differently?

**Comment by paul-gauthier** [comment]
This is the AskCoder:

https://github.com/Aider-AI/aider/blob/main/aider/coders/ask_coder.py

Depends which edit format you are using in "code" mode. But it would be one of the other _coder.py files.

You'll note that the AskCoder actually has none of its own code, while the others do.
