### ISSUE TITLE
Feature request: support for llama.cpp

### ISSUE THREAD

**Issue by kolinfluence** [Aider-AI/aider#2209]
llama.cpp running in server mode, how to use this? any documentation on usage?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/llms/openai-compat.html

**Comment by kolinfluence** [comment]
@paul-gauthier thx for making aider possible.

i saw the doc but seemed limited. anyone have any tutorial to set up from scratch? a youtube link maybe?

**Comment by BecoKo** [comment]
Hi!
This is my llama.cpp setup on windows PC:

1. Create aider [model settings file](https://aider.chat/docs/config/adv-model-settings.html):

`ModelMetaDataFile.json`
```
{
    "Phi-3-mini-4k-instruct-q4": {
        "max_tokens": 4096,
        "max_input_tokens": 4096,
        "max_output_tokens": 4096,
        "input_cost_per_token": 0.00000014,
        "output_cost_per_token": 0.00000028,
        "litellm_provider": "openai",
        "mode": "chat"
    },
    "Qwen2.5-Coder-7B": {
        "max_tokens": 60000,
        "max_input_tokens": 60000,
        "max_output_tokens": 60000,
        "input_cost_per_token": 0.00000014,
        "output_cost_per_token": 0.00000028,
        "litellm_provider": "openai",
        "mode": "chat"
    }
}
```

2. run llama.cpp:

`C:\llama.cpp\llama-server.exe --model Phi-3.5-mini-instruct.Q4_K_M.gguf --port 8099 --n-gpu-layers 100 --ctx-size 4096 --threads 8 --batch-size 1 --flash-attn`

3. run aider :

```
cd <repo folder>
C:\Python\aider-venv\Scripts\aider --openai-api-base http://127.0.0.1:8099/ --openai-api-key NONE --model openai/Phi-3-mini-4k-instruct-q4 --model-metadata-file C:\Python\aider-venv\ModelMetaDataFile.json --no-auto-commits --map-tokens 1024
```

**Comment by sirus20x6** [comment]
listen I don't know python and literally wrote that while drunk. it seems to work but it's probably not good enough to be merged

**Comment by akumaburn** [comment]
Can we re-open this? I don't understand why Ollama is supported but the actual back-end for it isn't? I've tried running it but it seems to incorrectly detect that the token limit was hit: 

```
aider --openai-api-base http://127.0.0.1:8012/   --openai-api-key NONE   --model openai/wanlige-li-14b-Q4_K_S   --model-metadata-file /mnt/xfs_raid0/ModelMetaDataFile.json   --no-auto-commits   --map-tokens 1024 --verbose

Model openai/wanlige-li-14b-Q4_K_S has hit a token limit!
Token counts below are approximate.

Input tokens: ~5,471 of 98,304
Output tokens: ~1 of 98,304
Total tokens: ~5,472 of 98,304
```

**Comment by BecoKo** [comment]
@akumaburn what options do you use to run the llama-server?
Do you use the following settings for Qwen2.5 based model:
`--ctx-size  98304 --rope-scaling yarn --rope-scale 4`

**Comment by Adam-Alj** [comment]
For anyone else coming across this, because I just spent the last hour+ flailing trying to solve this.

The docs *do* state that you should set an `OPENAI_API_KEY` environment variable. You may think that because you're running a local model, this can be optional or an empty string. You would be *wrong*. 

Set it to some arbitrary non-empty value. Otherwise, you'll just end up with the following, relatively unhelpful error message even on verbose mode:
```
litellm.APIError: APIError: OpenAIException - Connection error.
```

Stumbled across the answer in this open issue: https://github.com/Aider-AI/aider/issues/3018#issue-2812837423
