### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by yangboz** [Aider-AI/aider#2212]
### Issue

after install it by pip install -U aider-chat in conda py310, it throws error as following:

```
 from aider.main import main
  File "/opt/homebrew/lib/python3.11/site-packages/aider/main.py", line 24, in <module>
    from aider.report import report_uncaught_exceptions
  File "/opt/homebrew/lib/python3.11/site-packages/aider/report.py", line 11, in <module>
    from aider.versioncheck import VERSION_CHECK_FNAME
  File "/opt/homebrew/lib/python3.11/site-packages/aider/versioncheck.py", line 6, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
```
any idea? thanks.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. 

How did you install aider? What environment are you using? It looks like you don't have the correct set of dependencies installed. This doc may be helpful:

https://aider.chat/docs/troubleshooting/imports.html

I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
