### ISSUE TITLE
Q?: Why is the cache being warmed with 23K when I have no files loaded?

### ISSUE THREAD

**Issue by 5ocworkshop** [Aider-AI/aider#2215]
### Issue

I was using aider for a few minutes and then the phone rang.  I knew it might be a longer call so I decided to drop my files from the chat, thinking that if I was sitting idle at the prompt with no files loaded, it wouldn't need anything warm in the cache.  

Then I came back to this on the console, which lead to some questions:

```
> /drop aider/coders/chat_chunks.py                                                                                                                                                                              

Removed aider/coders/chat_chunks.py from the chat
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 0 cached tokens.
Warmed 21k cached tokens.                                                                                                                                                                                        
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
Warmed 21k cached tokens.
```
Does it make sense to be keeping the cache warm when there are new files?  I am assuming the 21K must be chat history and other hidden prompt things and the repo-map?

Also, this sequence jumped out at me, any idea what is happening here?

```
Warmed 21k cached tokens.
Warmed 0 cached tokens.
Warmed 21k cached tokens. 
```  

### Version and model info

Aider v0.60.1
Main model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite output
Weak model: claude-3-haiku-20240307
Git repo: .git with 361 files
Repo-map: using 1024 tokens, files refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Aider keeps the existing cache warm, whatever it last sent to the API.

**Comment by 5ocworkshop** [comment]
Thank you, good to know.
