### ISSUE TITLE
Uncaught SwitchCoder in commands.py line 1044

### ISSUE THREAD

**Issue by RickCarlino** [Aider-AI/aider#2232]
Aider version: 0.61.0
Python version: 3.10.12
Platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.35
Python implementation: CPython
Virtual environment: No
OS: Linux 6.8.0-47-generic (64bit)
Git version: git version 2.34.1

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
  File "main.py", line 808, in main
    coder.run(with_message=message_from_file)
  File "base_coder.py", line 732, in run
    self.run_one(with_message, preproc)
  File "base_coder.py", line 775, in run_one
    message = self.preproc_user_input(user_message)
  File "base_coder.py", line 764, in preproc_user_input
    return self.commands.run(inp)
  File "commands.py", line 236, in run
    return self.do_run(command, rest_inp)
  File "commands.py", line 208, in do_run
    return cmd_method(args)
  File "commands.py", line 1021, in cmd_code
    return self._generic_chat_command(args, self.coder.main_model.edit_format)
  File "commands.py", line 1044, in _generic_chat_command
    raise SwitchCoder(
aider.commands.SwitchCoder

```

# Repro

```
aider --subtree-only --no-show-model-warnings --yes --message-file test.md
```

**Comment by bwehrle** [comment]
Plus one- this happens when I use the `--load` command line switch to run a file with interactive commands

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Unfortunately not all of the `/` commands will work in a `/load` script. The `/switch` command is one of them.

**Comment by bwehrle** [comment]
In my script, I'm not using the `/switch` command.  I'm only using the `/code` command; is that not intended to work either?
My use cases is that I want to script aider through a command file.  Should I instead be using just stdin?

**Comment by RickCarlino** [comment]
Agreed with @bwehrle - My script did not use the `/switch` command. It had a `/add` and `/code` command, though. Additionally, it was using multi-line input via { }.

**Comment by fr34k8** [comment]
Same for me guys. thought aider detected this. anyway. 
@bwehrle same goes for me. I've a long list for aider to do, based on instructions and fine-tuning. 

@paul-gauthier I just filled two tickets, cause last ticket filled, was solved by using the main branch ;)

https://aider.chat/docs/usage/commands.html does not reference a /switch command or am I missing something?

**Comment by popstas** [comment]
Same: 2-lines loaded file with /add and /code

**Comment by paul-gauthier** [comment]
Ya, the `/code` command is not currently supported when loading commands from a file.
