### ISSUE TITLE
New files cannot be created

### ISSUE THREAD

**Issue by makecontact** [Aider-AI/aider#2238]
### Issue

When aider wants to create a new file, it can't and reports:

/***/src/app/strategy/page.tsx: unable to read: [Errno 2] No such file or directory: '***/src/app/strategy/page.tsx'
[Errno 2] No such file or directory: '/***/src/app/strategy/page.tsx

This started happening with 0.61.

**Comment by bearjaws** [comment]
What is the fix for this? I think its something I broke after I upgraded to .61 but not sure.

**Comment by paul-gauthier** [comment]
This should be fixed in the latest version. You can get it like this:

```
aider --upgrade

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
```

If you have a chance to try it, let me know if it works better for you.

**Comment by bearjaws** [comment]
Thank you @paul-gauthier that fixed it
