### ISSUE TITLE
Incorrect tokens logging occasionally

### ISSUE THREAD

**Issue by dopper** [Aider-AI/aider#2274]
### Issue

When sending content using sonnet I have noticed that often but not always the number of tokens sent appears to be double. When looking at the logs in the API client it shows the correct amount. Here is a recent example:
- Tokens: 216k sent, 108k cache write, 1.4k received. Cost: $0.75 message, $0.79 session.

In this case the 108k cache write matches the tokens sent, but Aider is doubling this value which produces and incorrect estimate cost. I think this just started happening after 0.62.

### Version and model info

Aider v0.62.1
Main model: claude-3-5-sonnet-20241022 with architect edit format, prompt cache, infinite output
Editor model: claude-3-5-sonnet-20241022 with editor-diff edit format
Weak model: claude-3-5-haiku-20241022
Git repo: .git with 736 files
Repo-map: using 2048 tokens, files refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How do you know only 108k were sent?

**Comment by dopper** [comment]
Hi, I was comparing token output from Aider to logs from LLM provider to look for discrepancies.
