### ISSUE TITLE
Is there a --silent mod?

### ISSUE THREAD

**Issue by raffeyang** [Aider-AI/aider#2281]
### Issue

- Normal:

![CleanShot 2024-11-07 at 15 54 31@2x](https://github.com/user-attachments/assets/69fc5471-9490-42ab-8901-1058a170e678)

- Silent:

![CleanShot 2024-11-07 at 15 56 03@2x](https://github.com/user-attachments/assets/9be0fae6-87b0-4c76-81c7-9303d608f950)

How can I remove or hide the welcome information? I think it's helpful to add something like 
```bash
aider --silent
```
or set the `.env` file.
```env
silent = true
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Why would you like to hide this info?

**Comment by raffeyang** [comment]
> Thanks for trying aider and filing this issue.
> 
> Why would you like to hide this info?

Because I want to program without distractions, I need the simplest interface, and I think this will be helpful for many people.

**Comment by therealtimex** [comment]
How come it's not helpful info?

**Comment by ericrafalovsky** [comment]
One use case where suppressing this output would be helpful is when invoking aider programmatically—such as in the shell scripting example on [Aider’s scripting documentation](https://aider.chat/docs/scripting.html)—to avoid repeatedly printing the header output.

**Comment by p-wegner** [comment]
I agree, i'm scripting with aider and in some cases having an option to turn off welcome messages and command confirmations + token usage summaries (e.g. for /clear, /drop, /add, ...) in general would be helpful. Currently i have to rely on heuristics to extract the actual llm responses when parsing aiders output.

**Comment by greyHairChooseLife** [comment]
Additionally, I would like the option to control the output of the following elements:

- Read-only files
- Added files
- SEARCH/REPLACE

The reason for needing a silent option for items 1 and 2 is that when the list becomes lengthy, it occupies too much space in the window. Moreover, we have the /ls command.

For item 3, a silent option is necessary to respect workflows that compare file changes within the editor (personally, I use the Vim editor). Even outside the editor, it allows for the use of other methods, such as delta, to review code changes.

**Comment by it-is-wednesday** [comment]
Hey, I was just writing a script where I'm feeding Aider's output into another program, and I need to wrangle its output through `tail -n +7` to get rid of the couple first lines. Would be cool to have a flag!
