### ISSUE TITLE
Architect mode and adding files

### ISSUE THREAD

**Issue by david-strejc** [Aider-AI/aider#2283]
### Issue

We are used to not adding files directly via /add or on cli - but instead aider finds  them out using repomap - but in architect mode when I don't add anyfile O1 responds but coder is not coding because there are no added files - there is only confirmation for adding files which is not adding any files currently - I don't know if this is happening all the time.

**Comment by paul-gauthier** [comment]
Ah, I see what you are saying. I will have a fix soon.

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
