### ISSUE TITLE
xai model not being recognized

### ISSUE THREAD

**Issue by Hecto-r** [Aider-AI/aider#2295]
### Issue

> /model xai/grok-beta

Warning for xai/grok-beta: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- xai/grok-beta
Aider v0.62.1
Model: xai/grok-beta with whole edit format
Git repo: .git with 79 files
Repo-map: disabled

I have my api key set using
Setx XAI_API_KEY

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/troubleshooting/warnings.html

**Comment by PhunkyBob** [comment]
## My workaround
Before:
```
λ aider --model xai/grok-beta --edit-format diff
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning for xai/grok-beta: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- xai/grok-beta
You can skip this check with --no-show-model-warnings
```

Workaround:
```
λ pip install -U litellm
...
Installing collected packages: openai, litellm
  Attempting uninstall: openai
    Found existing installation: openai 1.53.0
    Uninstalling openai-1.53.0:
      Successfully uninstalled openai-1.53.0
  Attempting uninstall: litellm
    Found existing installation: litellm 1.51.2
    Uninstalling litellm-1.51.2:
      Successfully uninstalled litellm-1.51.2
...
Successfully installed litellm-1.52.1 openai-1.54.3
```
(ignore warnings saying that there is a conflict with `aider-chat`)

Then: 
```
λ aider --model xai/grok-beta --edit-format diff
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.62.1
Model: xai/grok-beta with diff edit format
Git repo: .git with 2 files
Repo-map: disabled
Use /help <question> for help, run "aider --help" to see cmd line args
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
diff>
```


And this model is pretty nice for coding!

**Comment by montvid** [comment]
The xai grok-beta llm now has an openai api. Could someone add support to it via "openai/"? Using OpenAi api seems to require less tokens than xai/grok-beta api.
Sample code from xai:
`curl https://api.x.ai/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer KEY" -d '{
  "messages": [
    {
      "role": "system",
      "content": "You are a test assistant."
    },
    {
      "role": "user",
      "content": "Testing. Just say hi and hello world and nothing else."
    }
  ],
  "model": "grok-beta",
  "stream": false,
  "temperature": 0
}'`

**Comment by montvid** [comment]
@paul-gauthier it is called "grok" 2 beta not "groq" that's a different one. litellm has an option xai/grok-beta but the api uses too many tokens comparing to "openai/grok-beta" I defined myself (just wrote "grok-beta" after "openai/"). There is no config for openai/grok-beta and I don't know how to make one but would be nice someone made one.

**Comment by PhunkyBob** [comment]
@montvid I don't understand why you say `openai/grok-beta`, whereas `openai` is not the provider of `grok-beta`, but `xai` is.
In my understanding, it's `provider/model_name`, not `api_type/model_name`.

We should have a `xai\grok-beta` model, that uses OpenAI **format** API, but the provider is still xAI.
It's already supported by LiteLLM, but why would it cost more token?

**Comment by montvid** [comment]
@PhunkyBob I figure they use different api's xai\grok-beta vs openai/grok-beta. In Aider/litellm "openai/" means use openai compatible api. The openai compatible api was revealed only in November so I thinks it's a new api.

**Comment by PhunkyBob** [comment]
>  In Aider/litellm "openai/" means use openai compatible API

Is it?
When I use "openrouter/something", it uses openai compatible API, but with openrouter provider.
