### ISSUE TITLE
Duplicate declarations sneaking in to code

### ISSUE THREAD

**Issue by 5ocworkshop** [Aider-AI/aider#2317]
### Issue

I'm repeatedly finding duplicate declarations, usually functions or classes, sneaking in to code that aider is working on.  These are files that aider is the only editor of.  Is anyone else seeing this?  It makes debugging very challenging, as you might imagine.  This has been going on since 0.60.0 for me.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

What model?

**Comment by p-wegner** [comment]
I've seen this happen with latest sonnet and haiku, especially when diff edit format failed and the retry tries to recover. Although the recovery mechanism works, it leaves me with some duplicate declaration from time to time. Hard to pin down or create reproduceable cases though.
