### ISSUE TITLE
repomap assumption that identifiers are reasonably unique breaks down in large codebases

### ISSUE THREAD

**Issue by jbellis** [Aider-AI/aider#2341]
### Issue

I'm investigating why repomap quality is terrible when editing Cassandra.  It looks like the primary reason is that repomap can't distinguish between Foo.X and Bar.X.  So we end up with the top ranked definition
```
    [
        [
            "src/java/org/apache/cassandra/index/sai/analyzer/filter/FilterPipelineTask.java",
            "setLast"
        ],
        0.0026828027657769607
    ],
```

which is almost completely irrelevant.

This happens is because FilterPipelineTask has a method `getName`, which is a VERY common method in the codebase, and also FilterPipelineTask has no out-edges at all.  So it gets a ton of pagerank and ends up at the top.

Approximately all of the top ranked definitions are like this, that is, they are artifacts of ident collision and not "top definitions" in the intended sense of being useful in navigating the codebase.

**Comment by mm-zacharydavison** [comment]
aha, I also found this bug today while writing an alternative ranking strategy.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Yes, this is a known issue. The repomap relies on this heuristic, but it does break down for some symbols and some code bases.
