### ISSUE TITLE
repomap "distribute the rank from each source node, across all of its out edges" is unnecessary

### ISSUE THREAD

**Issue by jbellis** [Aider-AI/aider#2342]
### Issue

This is approximately the same as doing another iteration of pagerank.  Simplifying to derive ranked_definition from the graph weights (instead of doing additional manual arithmetic) would improve clarity and possibly performance.  (Not sure if this is a bottleneck.)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Nodes are files, edges are symbols with the direction being from the reference of the symbol to the definition of the symbol. That code is determining the final weight/score/rank of the *symbols*.
