### ISSUE TITLE
Aider doesn't seems to recognize changes I've made after adding the file to the chat during the same chat session

### ISSUE THREAD

**Issue by spikeliu1984** [Aider-AI/aider#2353]
### Issue

Hi, I'm new to Aider, from my observations of using Aider in 'Ask' chat mode, it doesn't seem to recognize changes I've made after adding the file to the chat during the same chat session. Is this the intended behavior of Aider?

Additionally, when I paste the edited class back into the chat, new lines in the code appear to trigger the message to be sent automatically. Is there a way to prevent this from happening?

Aider v0.62.1
Using Aider inside JetBrains Rider's terminal

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

https://aider.chat/docs/usage/commands.html#entering-multi-line-chat-messages

Aider always loads the latest version of the files from the file system when it sends each chat message.

**Comment by spikeliu1984** [comment]
Thanks for the reply, I'll close the issue.
