### ISSUE TITLE
Consider improving /architect capabilities by adding RAG/Local Vector store for large codebases

### ISSUE THREAD

**Issue by francescomagalini** [Aider-AI/aider#2357]
By complementing /architect mode with a more contextualized vision of potentially large codebases we improve /architect mode.
Does this make sense?
Thank you for developing aider.

**Comment by itlackey** [comment]
Maybe integrating the repo map with chunks of the actual code using something like LightRag could be helpful
https://github.com/HKUDS/LightRAG
