### ISSUE TITLE
Config read: should import directories recursively

### ISSUE THREAD

**Issue by ShawnSack** [Aider-AI/aider#2373]
### Issue

When adding a directory to the "read:" setting in .aider.conf.yml, get error: 
> unable to read: [Errno 21] Is a directory

Expectation: Aider will recursively add files in directory

Config excerpt: 
```
read:
  - conventions.md
  - src/docs/

```

### Version and model info

Aider: 0.63.0

**Comment by paul-gauthier** [comment]
This is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by ShawnSack** [comment]
It works! Thank you so much!

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
