### ISSUE TITLE
Please add support for new model gemini/gemini-exp-1114 (maybe soon also on Vertex AI)

### ISSUE THREAD

**Issue by Jasmin68k** [Aider-AI/aider#2374]
### Issue

Hello!

There's a new Gemini model available on https://ai.google.dev/gemini-api/docs/models/experimental-models. Please add.

On Vertex AI https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/gemini-experimental there still is the old experimental Gemini model. They might soon upgrade to the new one as well, in which case, please add that, too.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

This should be available in the latest version. You can get it like this:

```
aider --upgrade

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
```

If you have a chance to try it, let me know if it works better for you.

**Comment by Jasmin68k** [comment]
Thanks!

Works fine.

This seems to be more of a Pro than a Flash model, so maybe it should use `diff-fenced` edit format, instead of whole.
