### ISSUE TITLE
Issue: "clear chat history" button is browser doesn't clear

### ISSUE THREAD

**Issue by AdrianAcala** [Aider-AI/aider#2375]
### Issue

When using browser, you stop the request midway. Afterwards, it doesn't allow you to click the button "clear chat history". You may want to check if other functionality isn't reset either.
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/5359b850-13fe-45d8-9ba8-5d15ef76e9dd">

### Version and model info

Aider v0.63.1
Model: ollama/qwen2.5-coder:32b with diff edit format

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It doesn't erase the content from the browser, but it clears it from aider's internal memory.

**Comment by AdrianAcala** [comment]
@paul-gauthier , thanks so much for everything you do! I went through your LinkedIn out of your curiosity and totally appreciate the work you put into the project.

As for the issue, the button is disabled which is what I meant. It's not clickable. I have to reload the page and it becomes clickable again.
