### ISSUE TITLE
Cross-region Bedrock model identifiers do not work

### ISSUE THREAD

**Issue by nsfinkelstein** [Aider-AI/aider#2392]
### Issue

Running `aider --list-models bedrock/` returns a list including `bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0`.

However when I run `aider` with that model I see the following issue:

```
litellm.NotFoundError: BedrockException - Bedrock HTTPX: Unknown provider=us, model=us.anthropic.claude-3-5-haiku-20241022-v1:0
```

It looks like the code is trying to interpret the `us.` prefix as a model provider, but it is the prefix used for cross-region inference.

### Version and model info

Aider: v0.63.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

That error looks like it is coming directly from bedrock.

**Comment by nsfinkelstein** [comment]
Thanks. This was resolved with `pip install -U litellm`, as per [this comment](https://github.com/Aider-AI/aider/issues/2120#issuecomment-2437709586) on a related issue. I'll close this issue.
