### ISSUE TITLE
add "(D)on't ask again" to "Add .aider* to .gitignore (recommended)?"

### ISSUE THREAD

**Issue by monperrus** [Aider-AI/aider#2397]
### Actual behavior:

Add .aider* to .gitignore (recommended)? (Y)es/(N)o [Yes]

### Expected behavior:

Add .aider* to .gitignore (recommended)? (Y)es/(N)o/(D)on't ask again [Yes]

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/config/options.html#--gitignore
