### ISSUE TITLE
Model context data and price for openrouter/openai/gpt-4o-mini not correctly translated

### ISSUE THREAD

**Issue by fcnjd** [Aider-AI/aider#2399]
### Issue

Whenever I just invoke aider with --4o, it works seamlessly. But with openrouter the model isn't recognized, although I checked so often that I can't really see a typo in my command:
$ aider.exe --model openrouter/openai/gpt-4o .
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning for openrouter/openai/gpt-4o-mini: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- openrouter/openai/gpt-4
- openrouter/openai/gpt-4o
- openrouter/openai/o1-mini

### Version and model info

(base)
Julian@Julians-PC MINGW64 ~
$ aider.exe --version
aider 0.63.2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

It's not warning you about gpt-4o, it's warning you about *mini*, which is used as the weak model for 4o: `openrouter/openai/gpt-4o-mini`.

**Comment by fcnjd** [comment]
@paul-gauthier Thank you very much for your quick answer, that narrows down the problem. I correspondingly changed the issue title. However, since aider correctly retrieves model context and pricing for openai/gpt-4o-mini, but not for OpenRouter, I think it makes sense to leave this issue open.

**Comment by paul-gauthier** [comment]
You can add the metadata for whichever models you like:

https://aider.chat/docs/config/adv-model-settings.html#context-window-size-and-token-costs
