### ISSUE TITLE
RepoMap pageranking improvement, especially in large monorepos.

### ISSUE THREAD

**Issue by mm-zacharydavison** [Aider-AI/aider#2405]
### Issue

Background:

I'm currently working on a tool that automatically fixes TypeScript compilation errors in a large monorepo (800k lines) by scripting `aider` (we are enabling strict mode, and have 10,000+ errors to fix).

The approach I have works well for simple fixes, but `aider` is consistently 'blind' to the types that are directly imported from the target files (which contain the types it would need to understand to fix most issues).

I took a look at the repo map that gets output, and it's dominated by common aliases / imports that occur a lot in the codebase, and with 5000 tokens, nothing within a graph distance of even 1 (e.g. direct imports) is present, which means `aider` is completely blind to the most important information.

After looking at the implementation of [RepoMap](https://github.com/Aider-AI/aider/blob/dba844c7f96ff05ca0ea76659a2f521689d0d324/aider/repomap.py#L226), it looks to me like actually, it is intended to weight references heavily, and this probably works in smaller repos.

I'd like to improve this use case. I'm happy to experiment and open PRs to `aider`, but I wanted to ask your thoughts first before I proceed, as per CONTRIBUTING.md.

This may be solvable through tweaking the weights (and just allowing those weights to be customized by the end user).

This is a fairly naive approach:

```python
        # Determine weight multiplier
        if ident in mentioned_idents:
            mul = 10
        elif ident.startswith('_'):
            mul = 0.1
        else:
            # Here's where we can boost direct imports from chat files
            referencer_is_chat_file = referencer in chat_rel_fnames
            if referencer_is_chat_file:
                mul = 50  # Much higher weight for references from chat files
            else:
                mul = 1
```

But essentially we'd want higher weights for files that are closer to the current file.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Interesting approach. Does that change help you use case?

Also, this doc may be helpful in case you haven't seen it:

https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo

**Comment by jbellis** [comment]
related: https://github.com/Aider-AI/aider/issues/2341

**Comment by paul-gauthier** [comment]
Just checking back to see if this approach panned out?

**Comment by mm-zacharydavison** [comment]
It's working, but I need to do a bit more work on it before I'm ready to open a PR, and I've been sidelined by some other work for the moment. I'll be coming back to it soon.

You can close this issue if you'd like, I'll open a PR when its ready.

**Comment by NICK-DUAN** [comment]
same problem, expect pr
