### ISSUE TITLE
unrecognized arguments: --openrouter-api-key

### ISSUE THREAD

**Issue by hyperknot** [Aider-AI/aider#2407]
### Issue

I have aider 0.63.2. I'm entering 
```
openrouter-api-key: sk-or-...
```

into my .aider.conf.yml

This happens when I start the app.

```
aider: error: unrecognized arguments: --openrouter-api-key=sk-or-...
```

anthropic-api-key is next to it and it works correctly, it's only openrouter which isn't. I think the yml parsing might have been missed for openrouter?

it works with .env file

### Version and model info

aider 0.63.2

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/config/dotenv.html#storing-llm-keys

**Comment by hyperknot** [comment]
anthropic and openai works like that. openrouter does not.

**Comment by hyperknot** [comment]
It's not stale, please fix it.

**Comment by paul-gauthier** [comment]
As the docs say, only openai and anthropic have command line args for keys. Keys for all other providers are set via environment variables.

**Comment by hyperknot** [comment]
But why is there a differentiation? Of course cli args make no sense for keys, but why no support in the config file?

I like to be able to start aider in any project folder on my computer, without having to set up anything. Global config works perfectly for this, except for the need to specify openrouter api key in local .env file.

So now I have to pollute my project folders with .env files all containing the openrouter key.

It'd be really great if the config file would support all providers identically.

**Comment by paul-gauthier** [comment]
You can just put a .env file in your home dir?
