### ISSUE TITLE
It always asking to continue using Sonnet 3.5

### ISSUE THREAD

**Issue by PierrunoYT** [Aider-AI/aider#2408]
### Issue

It always asking to continue using Sonnet 3.5
![grafik](https://github.com/user-attachments/assets/882a3754-5420-4371-afab-583b61a11f84)
![grafik](https://github.com/user-attachments/assets/3fa73fc9-0e56-4b1e-b408-3b2779942f42)

### Version and model info
aider 0.63.1
Sonnet 3.5
aider --model openrouter/anthropic/claude-3.5-sonnet --no-suggest-shell-commands --no-pretty

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

What does `/tokens` tell you when this happens?

**Comment by PierrunoYT** [comment]
> Thanks for trying aider and filing this issue.
> 
> What does `/tokens` tell you when this happens?

![grafik](https://github.com/user-attachments/assets/c61df5c0-442b-4822-821b-bf546bca051a)
