### ISSUE TITLE
Improving Aider benchmark

### ISSUE THREAD

**Issue by RalphMao** [Aider-AI/aider#2411]
### Issue

Sharing some thoughts on how to make Aider benchmark closer to real development and detecting potential overfitting issues. During the trials, the aider agent should not have access to the unit tests, but be asked to write its own tests and iterate over the solution. The "oracle" unit tests are only used during final scoring.

1. Closer to real development - fornew features, there is no guarantee of the availability of "oracle" tests. Especially for complex problems, setting the test boundary is as challenging as implementing the features.
2. Detect potential overfitting - we can ask an LLM judge, similar to MT-bench, to evaluate the similarity between the written tests and official unit tests. Higher similarity implies higher possibility of overfitting.

What's your thoughts on this idea? I can go ahead and make PRs if this idea is echoed by other folks.

**Comment by Kreijstal** [comment]
> ### Issue
> 
> Sharing some thoughts on how to make Aider benchmark closer to real development and detecting potential overfitting issues. During the trials, the aider agent should not have access to the unit tests, but be asked to write its own tests and iterate over the solution. The "oracle" unit tests are only used during final scoring.
> 
>     1. Closer to real development - fornew features, there is no guarantee of the availability of "oracle" tests. Especially for complex problems, setting the test boundary is as challenging as implementing the features.
> 
>     2. Detect potential overfitting - we can ask an LLM judge, similar to MT-bench, to evaluate the similarity between the written tests and official unit tests. Higher similarity implies higher possibility of overfitting.
> 
> 
> What's your thoughts on this idea? I can go ahead and make PRs if this idea is echoed by other folks.
> ### Version and model info
> 
> _No response_

I like this idea but that is indeed a different benchmark, not the same

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The purpose of the benchmark is to assess the LLM's ability to edit code. You may want to look at SWE Bench for a more general "coding" benchmark.

**Comment by Kreijstal** [comment]
> Thanks for trying aider and filing this issue.
> 
> The purpose of the benchmark is to assess the LLM's ability to edit code. You may want to look at SWE Bench for a more general "coding" benchmark.

I mean eventually aider benchmark is going to saturate, we are at 84%, which is still a long way to go, but once we start hitting 95% maybe it's time to start thinking about other benchmarks, aider benchmark is still safe.
