### ISSUE TITLE
Alias and environement variables from ~/.bashrc are not available from /run

### ISSUE THREAD

**Issue by DanaelP** [Aider-AI/aider#2415]
### Issue

Hello,

I am not able to use alias and environment variables set in ~/.bashrc when using /run in aider. The fix I found is to add interactive option "-i" to the shell in run_cmd_pexpect function of run_cmd.py as follow:
`child = pexpect.spawn(shell, args=["-i", "-c", command], encoding="utf-8")`

version: 0.63.2

**Comment by DanaelP** [comment]
Hello @paul-gauthier, 

Thanks for your fast reply and fix. I've been able to test and it's working well for the environment variables. However, aliases are still not recognized.

simple test is to add following alias in ~/.bashrc :
alias ll="ls -l"

Then try run it through aider:
> /run ll                                                                                                  

/bin/bash: line 1: ll: command not found

Thanks

**Comment by paul-gauthier** [comment]
Sorry, I reverted this but probably should have kept it. It's back in the main branch now.

**Comment by DanaelP** [comment]
It's working well. Thanks @paul-gauthier
