### ISSUE TITLE
Feature: allow ad hoc chat mode for `/editor`

### ISSUE THREAD

**Issue by thehunmonkgroup** [Aider-AI/aider#2418]
Currently, `/editor` operates in the selected chat mode. Similar to using `/ask` when in code mode, it would be nice if the `/editor` command could be invoked with an ad hoc chat mode.

I see a couple of ways to attack this, each with trade offs:

1. **Allow chat mode commands inside the editor:** Similar to how the main interface works, if the text in the editor starts with a chat mode command (like `/ask`), then switch to that mode for that input. This would be most familiar to people, but from my look, I think it would require a substantial refactor, because you'd essentially be running a command inside a command.
2. **Pass chat mode as an arg to `/editor`:** Less familiar syntax, but more straightforward to implement. Validation of the argument should be pretty straightforward.

I'm happy to take a crack at the PR for this, but do not want to start until we've decided on a best approach.

@paul-gauthier thoughts?

**Comment by paul-gauthier** [comment]
Ya, neither approach is super attractive. I probably think this is best left as something to be done in 2 commands.

**Comment by thehunmonkgroup** [comment]
> Ya, neither approach is super attractive. I probably think this is best left as something to be done in 2 commands.

I can let this go. Sadly, it's currently three commands (switch to new mode, run editor, switch back to original mode), and that adds up over time.

**Comment by paul-gauthier** [comment]
Give the main branch a try. Now when you exit the editor, it simply prefills the text into the prompt. You press enter to submit it. So now it can contain /commands which will run.

This allows you to make a file like:

```
/ask 

For something...
...long and complicated
```

**Comment by thehunmonkgroup** [comment]
You nailed it, that's the perfect solution.
