### ISSUE TITLE
Uncaught OSError in pathlib.py line 1116

### ISSUE THREAD

**Issue by arthur-brainchain** [Aider-AI/aider#2421]
Aider version: 0.63.2
Python version: 3.11.5
Platform: macOS-14.6.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: No
OS: Darwin 23.6.0 (64bit)
Git version: git version 2.39.5 (Apple Git-154)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.aider'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 507, in main
    analytics = Analytics(logfile=args.analytics_log, permanently_disable=args.analytics_disable)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "analytics.py", line 35, in __init__
    self.get_or_create_uuid()
  File "analytics.py", line 74, in get_or_create_uuid
    self.load_data()
  File "analytics.py", line 82, in load_data
    data_file = self.get_data_file_path()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "analytics.py", line 70, in get_data_file_path
    data_file.parent.mkdir(parents=True, exist_ok=True)
  File "pathlib.py", line 1120, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
OSError: [Errno 30] Read-only file system: '/root'

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by arthurcolle** [comment]
oh nice what was the fix? I was wondering how I was the first to report this, was it related to Mac specific updates?

**Comment by paul-gauthier** [comment]
Looks like maybe you were running aider with your home dir on a read only filesystem?

Aider catches the error and works around it now.
