### ISSUE TITLE
it seems like absolute path from #152 stop working

### ISSUE THREAD

**Issue by wasdee** [Aider-AI/aider#2425]
### Issue

it seems like absolute path from #152 stop working

# context
i tried to drag a file into the aider shell, and it not recognize as an existing file.
```
> /add /home/ben/Devs/whale/Interfaces/WebAppSvelte/Dockerfile                                                                                                                                                              

No files matched ''/home/ben/Devs/whale/Interfaces/WebAppSvelte/Dockerfile''. Do you want to create /home/ben/Devs/whale/'/home/ben/Devs/whale/Interfaces/WebAppSvelte/Dockerfile'? (Y)es/(N)o [Yes]:                            
```

might due to single quote added auto.

### Version and model info

Aider v0.64.1
Main model: anthropic/claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite output
Weak model: anthropic/claude-3-5-haiku-20241022
Git repo: .git with 2,286 files
Warning: For large repos, consider using --subtree-only and .aiderignore
See: https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo
Repo-map: using 1024 tokens, files refresh
VSCode terminal detected, pretty output has been disabled.
Use /help <question> for help, run "aider --help" to see cmd line args

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can only `/add` files that are part of the repo. If they are, absolute paths should work:

```
$ aider
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.66.1.dev+less
Model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite output
Git repo: .git with 395 files
Repo-map: using 1024 tokens, files refresh
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /add /Users/gauthier/Projects/aider/README.md

Added README.md to the chat
```

If you want to include files from outside the repo, you can use `/read`.

**Comment by wasdee** [comment]
It's not that the aider doesn't accept the absolute path. 

It's that the cursor terminal automatically added the single quote to the absolute path. 

Thus, I'm suggesting that aider might add a feature to ignore those quote symbols ( ' " ) if present.

**Comment by paul-gauthier** [comment]
Aider supports double-quoted strings with `/add`.
