### ISSUE TITLE
Add ai-suggested commands to command history if executed, so can later be re-used

### ISSUE THREAD

**Issue by distbit0** [Aider-AI/aider#2427]
### Issue

Often I am using aider and it suggests a very useful command for e.g. running my code in a certain way, which I then accept. I have noticed though that despite accepting and executing these ai-suggested commands, they are not added to the aider up-arrow history and hence I can not easily search for them and re-execute them using ctrl+r or my up arrow.

I often find this very annoying and have to scroll up and manually look for the previously recommended command, then copy and paste it. Please automatically save it to the command history. many thx

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

What version of aider are you using? They should be added to history.

**Comment by distbit0** [comment]
Aider v0.62.1

**Comment by distbit0** [comment]
AH ok I upgraded and it is now working. I thought I was on the latest version as I had recently updated it w/ pip but I had a pip configuration issue which caused the update to fail.

**Comment by hopewise** [comment]
@distbit0 I am using aider `0.70.0`, on Mac, I do Command Up, Command Down, but it scroll up line by line, instead of jumping to previous message. p.s: I am using iTerm-2

**Comment by paul-gauthier** [comment]
This doc may be helpful:

https://aider.chat/docs/usage/commands.html#keybindings

**Comment by hopewise** [comment]
@paul-gauthier  I tried adding `--vim` when starting aider as:

```
 aider --deepseek --vim
```

but Ctrl-Up result into [Enter Mission Control](url) instead of Scroll back through previously sent messages
