### ISSUE TITLE
support gemini 1121

### ISSUE THREAD

**Issue by Kreijstal** [Aider-AI/aider#2430]
### Issue

I don't see it in the benchmarks is it supported? it's free

### Version and model info

gemini-1114

**Comment by Kreijstal** [comment]
I meant gemini-exp-1121, I apologize

**Comment by Kreijstal** [comment]
Also it seems the endpoints are vertex endpoints rather than ai studio endpoints?
https://generativelanguage.googleapis.com/v1beta/models/ ?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The quotas are so low it's very hard to benchmark at the moment.

**Comment by Kreijstal** [comment]
it got solved
