### ISSUE TITLE
Uncaught ValueError in base_coder.py line 159

### ISSUE THREAD

**Issue by iliagerman** [Aider-AI/aider#2431]
Aider version: 0.64.2.dev16+gfbadfcfa
Python version: 3.12.4
Platform: macOS-15.1.1-arm64-arm-64bit
Python implementation: CPython
Virtual environment: Yes
OS: Darwin 24.1.0 (64bit)
Git version: git version 2.39.3 (Apple Git-146)

An uncaught exception occurred:

```
Traceback (most recent call last):
  File "aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "main.py", line 861, in main
    coder.run()
  File "base_coder.py", line 741, in run
    self.run_one(user_message, preproc)
  File "base_coder.py", line 784, in run_one
    list(self.send_message(message))
  File "base_coder.py", line 1258, in send_message
    self.reply_completed()
  File "architect_coder.py", line 36, in reply_completed
    editor_coder = Coder.create(**new_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "base_coder.py", line 159, in create
    raise ValueError(f"Unknown edit format {edit_format}")
ValueError: Unknown edit format json

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You've named a non-existent edit format. Here's a doc that lists the valid edit formats:

https://aider.chat/docs/more/edit-formats.html

That said, aider should handle this more gracefully and not crash.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by iliagerman** [comment]
I installed the new version and the issue was not reproduced
