### ISSUE TITLE
REQ: Update the default GPT-4.0 model for command "--4o"

### ISSUE THREAD

**Issue by kck-4428** [Aider-AI/aider#2437]
### Request

Update the default model for the command aider --4o to use "gpt-4o", which is the latest version of GPT-4o available (instead of  specific version)

### Version info
Aider v0.64.1

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.
The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.

**Comment by paul-gauthier** [comment]
I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.
