### ISSUE TITLE
How to cancel chat when using `base_coder.py`'s Code class?

### ISSUE THREAD

**Issue by lee88688** [Aider-AI/aider#2455]
### Issue

when use [`run_stream`](https://github.com/Aider-AI/aider/blob/325cdfcf57780ef56e6f7e77f5d68333bd7313fc/aider/coders/base_coder.py#L715) and [`send_message`](https://github.com/Aider-AI/aider/blob/325cdfcf57780ef56e6f7e77f5d68333bd7313fc/aider/coders/base_coder.py#L1197) to interact with Code class, it seems there is no other api to stop chat except use throw `KeyboardInterrupt`.

when I use `chat = coder.send_message('xxx'); chat.throw(KeyboardInterrupt());` to throw exception, will the chat stop right now? or it is just stop iterator and keep the chat stream message background.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Sounds like you are trying to do some advanced scripting, which is not officially supported.

**Comment by lee88688** [comment]
is there any plan to do this?

**Comment by paul-gauthier** [comment]
Aider is not intended to be scripted in that way, so this is probably out of scope.

**Comment by lee88688** [comment]
thanks
