### ISSUE TITLE
Feature request: Referencing code

### ISSUE THREAD

**Issue by bogiva** [Aider-AI/aider#2456]
### Issue

Aider is a great tool, especially now with the architect mode, but my company is rejecting its use because it cannot be guaranteed that the output code does not contain copyrighted material or that it is released under permissive licenses.

Would it be possible to add a feature that checks (e.g. using some GitHub APIs or something) if the code generated by LLMs contain snippets from public repositories and if yes to also extract their license?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Maybe only use aider with an LLM that has this feature that you want?

**Comment by bogiva** [comment]
AFAIK there are no such models invented yet.
