### ISSUE TITLE
AIDER_READ environment variable does not have the same behavior as /read/

### ISSUE THREAD

**Issue by Trolann** [Aider-AI/aider#2459]
### Issue

I have created a conventions file `.aider.guidelines` in my home directory next to my `.env` file. 

`AIDER_READ=~/.aider.guidelines`

When starting up, I receive the following error
`Error: Read-only file /home/user/repo/~/.aider.guidelines does not exist. Skipping.`

Setting `AIDER_READ=../.aider.guidelines` does work, but will obviously break if my repo is not in my home dir. 

This is not a duplicate of #1155; the `/read ~/.aider.guidelines` works perfectly. The AIDER_READ= variable does not. How can this be fixed? 

### Version and model info

Aider v0.64.2.dev90+g13c5bfdd
Main model: claude-3-5-sonnet-20241022 with diff edit format, infinite output
Weak model: claude-3-5-haiku-20241022
Git repo: .git with 50 files
Repo-map: using 1024 tokens, auto refresh

**Comment by paul-gauthier** [comment]
The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.
