### ISSUE TITLE
Customize color of green horizontal line

### ISSUE THREAD

**Issue by joihn** [Aider-AI/aider#2466]
### Issue

The color of the Green horizontal line (spearation) is very similar to kitty terminal panel separation color, which create confusion. 
Any way to customize this color ?
![image](https://github.com/user-attachments/assets/3baaafe9-431a-4ec3-81d2-77977451e6e7)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. This doc may be helpful:

https://aider.chat/docs/config/options.html#output-settings

**Comment by 5ocworkshop** [comment]
Just a suggestion... could creating an LLM friendly version of the docs and making a custom GPT available to answer questions like this reduce the question volume?

**Comment by paul-gauthier** [comment]
https://aider.chat/docs/troubleshooting/support.html

**Comment by craftgear** [comment]
Bump.

> Thanks for trying aider and filing this issue. This doc may be helpful:

> https://aider.chat/docs/config/options.html#output-settings

Excuse me but what option in this doc changes green horizontal line color?

**Comment by craftgear** [comment]
@joihn Hi, did you successfully change the color?

**Comment by joihn** [comment]
Sorry for my lack of response in the past few weeks.
No, I did not manage, I also did not find it in the doc.

**Comment by craftgear** [comment]
@joihn  It's a shame but thanks for your reply.

**Comment by paul-gauthier** [comment]
`--user-input-color` controls the line color.

<img width="775" alt="2024-12-29_09-43-05" src="https://github.com/user-attachments/assets/c2f8e2e2-38df-4a94-a910-2f140f2878eb" />

**Comment by craftgear** [comment]
@paul-gauthier Nice! I finally could change the line color. Thank you so much👍
