### ISSUE TITLE
Feature Request: "Refine Plan" Option in Architect Mode

### ISSUE THREAD

**Issue by rubik** [Aider-AI/aider#2471]
### Issue

Architect mode is a valuable tool, but I often want to make minor/major adjustments to its proposed plans. Currently, the only options available once a plan is prepared are "Edit the files? (Y)es/(N)o [Yes]:".

I propose adding a third option, "Refine Plan," which would allow users to request modifications to the plan to the architect model before editing the files. This would streamline workflows by reducing the need for multiple file edits and LLM calls. My current workaround involves editing files and then requesting further changes from the architect, which is inefficient and time-consuming.

Thank you for considering this improvement to enhance the user experience.

### Version and model info

Aider v0.64.1
Main model: o1-preview with architect edit format
Editor model: anthropic/claude-3-5-sonnet-20241022 with editor-diff edit format
Weak model: gpt-4o-mini
Git repo: .git with 45 files
Repo-map: using 1024 tokens, files refresh

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can just answer "No" and then send a message like "Please refine the plan to ...".

**Comment by rubik** [comment]
@paul-gauthier Thank you for the quick reply. It makes sense; for some reason I thought that answering "No" would discard the plan.
