### ISSUE TITLE
Add a fix/continue option

### ISSUE THREAD

**Issue by tom-doerr** [Aider-AI/aider#2478]
I mostly run the command Aider suggests, get an error, hit enter to add the output to the chat and type fix or continue so Aider tries to fix the issue. Could we get a fix option that shows up every time there is a non-zero exit code that gets triggered with pressing f on the dialog that shows up after the output? Maybe it would be even better to add a continue option (c) that just adds the output to the chat and prompts Aider with 'continue' so it continues the work on the task. This could always be shown, not just for error, and would be useful for e.g. doing multiple iterations on refactoring, improving speed or making the output presentation prettier/cleaner.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

There used to be a more direct to have aider fix a failed run/test. But it was a different flow than if aider ran an LLM suggested shell command. This caused a lot of confusion for users.

I recently unified them all to a single flow, which I think is overall simpler and more predictable.

I just had it prefill "Fix that" into the next prompt if there's a non-zero exit status:

```
$ aider
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Aider v0.66.1.dev+less
Model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite output
Git repo: .git with 395 files
Repo-map: using 1024 tokens, files refresh
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /test false

Added 0 lines of output to the chat.
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> Fix that
```


The change is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.
