### ISSUE TITLE
Another Neovim Editor Plugin

### ISSUE THREAD

**Issue by aweis89** [Aider-AI/aider#2482]
### Issue

After using the existing neovim aider plugin (which was great), I've decided to build a different one with different features.
Namely, I didn't want aider to auto track all buffer files that are open.
- This  plugin integrates with a neovim fuzzy file picker to select one or multiple files to add
- It allows using visual mode text selection (highlighting text) in-conjunction with prompting for a question to /ask 
- It auto keeps the sessions alive when toggled so the context remains active

There are several AI plugins in Neovim for editing files and asking questions that I've used quite a bit. However, taking advantage of the incredible existing functionality of `aider`, and only focusing on the Neovim integration parts, enables easily building a plugin that surpasses them all. Thank you for building this incredible tool!

https://github.com/aweis89/aider.nvim

### Version and model info

It uses whatever `aider` command is in PATH, so it supports the latest version

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue and making a new editor integation!
