### ISSUE TITLE
Enormous token counts and costs for some messages 

### ISSUE THREAD

**Issue by tom-doerr** [Aider-AI/aider#2491]
### Issue

I often get enormous token counts for some messages and cost for some messages, even if I just ask a short question and the context shown by /tokens isn't large. This seems to happen when the Anthropic throws rate limit errors, but I'm not sure if it's because of the errors being thrown and resent so often or if Aider is sending so much that those errors are thrown. 
Most of what I'm paying seems to be due to messages like this:
![image](https://github.com/user-attachments/assets/410e9560-2da6-4329-817b-653705638b35)
![image](https://github.com/user-attachments/assets/39e5f9c2-fb16-43bd-9821-844a2ab8319f)

### Version and model info

Aider v0.65.1
Main model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite
output
Weak model: claude-3-5-haiku-20241022
Git repo: .git with 46 files
Repo-map: using 1024 tokens, files refresh
Added optimize_hyperparameters.py to the chat.
Added trial_executor.py to the chat.
Added utils/optimization.py to the chat.
Added visualization/model_analysis.py to the chat.
Restored previous conversation history.
Command Line Args:   --sonnet --vim --analytics --analytics-log analytics.log 
--cache-prompts --cache-keepalive-pings 4

Environment Variables:
  OPENAI_API_KEY:    ...U_UA
  ANTHROPIC_API_KEY: ...egAA

Defaults:
  --model-settings-file:.aider.model.settings.yml
  --model-metadata-file:.aider.model.metadata.json
  --env-file:        /home/tom/git/x_twitter_composio/.env
  --map-refresh:     auto
  --map-multiplier-no-files:2
  --input-history-file:/home/tom/git/x_twitter_composio/.aider.input.history
  --chat-history-file:/home/tom/git/x_twitter_composio/.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --tool-warning-color:#FFA500
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     /home/tom/git/x_twitter_composio/.aiderignore
  --lint-cmd:        []
  --test-cmd:        []
  --encoding:        utf-8
  --voice-format:    wav
  --voice-language:  en

Option settings:
  - aiderignore: /home/tom/git/x_twitter_composio/.aiderignore
  - alias: None
  - analytics: True
  - analytics_disable: False
  - analytics_log: analytics.log
  - anthropic_api_key: ...egAA
  - apply: None
  - apply_clipboard_edits: False
  - assistant_output_color: #0088ff
  - attribute_author: True
  - attribute_commit_message_author: False
  - attribute_commit_message_committer: False
  - attribute_committer: True
  - auto_commits: True
  - auto_lint: True
  - auto_test: False
  - cache_keepalive_pings: 4
  - cache_prompts: True
  - chat_history_file: /home/tom/git/x_twitter_composio/.aider.chat.history.md
  - chat_language: None
  - check_update: True
  - code_theme: default
  - commit: False
  - commit_prompt: None
  - completion_menu_bg_color: None
  - completion_menu_color: None
  - completion_menu_current_bg_color: None
  - completion_menu_current_color: None
  - config: None
  - dark_mode: False
  - detect_urls: True
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - editor: None
  - editor_edit_format: None
  - editor_model: None
  - encoding: utf-8
  - env_file: /home/tom/git/x_twitter_composio/.env
  - exit: False
  - fancy_input: True
  - file: None
  - files: []
  - git: True
  - gitignore: True
  - gui: False
  - input_history_file: /home/tom/git/x_twitter_composio/.aider.input.history
  - install_main_branch: False
  - just_check_update: False
  - light_mode: False
  - lint: False
  - lint_cmd: []
  - list_models: None
  - llm_history_file: None
  - load: None
  - map_multiplier_no_files: 2
  - map_refresh: files
  - map_tokens: None
  - max_chat_history_tokens: None
  - message: None
  - message_file: None
  - model: claude-3-5-sonnet-20241022
  - model_metadata_file: .aider.model.metadata.json
  - model_settings_file: .aider.model.settings.yml
  - openai_api_base: None
  - openai_api_deployment_id: None
  - openai_api_key: ...U_UA
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - read: None
  - restore_chat_history: False
  - show_diffs: False
  - show_model_warnings: True
  - show_prompts: False
  - show_release_notes: None
  - show_repo_map: False
  - skip_sanity_check_repo: False
  - stream: True
  - subtree_only: False
  - suggest_shell_commands: True
  - test: False
  - test_cmd: []
  - tool_error_color: #FF2222
  - tool_output_color: None
  - tool_warning_color: #FFA500
  - upgrade: False
  - user_input_color: #00cc00
  - verbose: False
  - verify_ssl: True
  - vim: True
  - voice_format: wav
  - voice_language: en
  - weak_model: None
  - yes_always: None

**Comment by etewiah** [comment]
Yes there does seem to be something peculiar going on.   I made a call which returned with this information:

```
Tokens: 114k sent, 92 received. Cost: $0.34 message, $0.67
session.
```

I then began to hit the rate limit:

```
litellm.RateLimitError: AnthropicException -
b'{"type":"error","error":{"type":"rate_limit_error","message":"
This request would exceed your organization\xe2\x80\x99s rate
limit of 20,000 input tokens per minute. For details, refer to:
https://docs.anthropic.com/en/api/rate-limits; see the response
headers for current usage. Please reduce the prompt length or
the maximum tokens requested, or try again later. You may also
contact sales at https://www.anthropic.com/contact-sales to
discuss your options for a rate limit increase."}}'
The API provider has rate limited you. Try again later or check
your quotas.
Retrying in 0.2 seconds...
```

I cancelled the above call ( I think with control-C).  I then added one small extra file and made the same call that had previously sent 114k  tokens.  This time it sent 915k tokens:


```
Tokens: 915k sent, 94 received. Cost: $2.75 message, $3.42
session.
```


This is the output I get when I run "/tokens"


```

Approximate context window usage for
anthropic/claude-3-5-sonnet-20241022, in tokens:

$ 0.0053    1,775 system messages
$ 0.0030    1,004 chat history
use /clear to clear
$ 0.0034    1,132 repository map
use --map-tokens to resize
$ 0.0054    1,811 src/router/routes.js
/drop to remove
$ 0.0038    1,250 data/examples/referencePropertyDetails.json
/drop to remove
$ 0.0036    1,194 src/pages/HtocLandingPage.vue
/drop to remove
$ 0.3065  102,178 data/examples/html/codefastLanding.html
/drop to remove
$ 0.0021      713
src/concerns/reference-properties/components/ReferencePropertySu
mmary.vue /drop to remove
$ 0.0050    1,668
src/concerns/reference-properties/pages/ReferencePropertiesList.
vue       /drop to remove
$ 0.0042    1,387
src/concerns/reference-properties/components/ReferencePropertyDe
tails.vue /drop to remove
==================
$ 0.3423  114,112 tokens total
           85,888 tokens remaining in context window
          200,000 tokens max context window size
```


### Version and model info

Aider v0.65.1
Main model: anthropic/claude-3-5-sonnet-20241022 with diff edit
format, infinite output
Weak model: anthropic/claude-3-5-haiku-20241022
Git repo: .git with 146 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> for help, run "aider --help" to see cmd
line args

**Comment by tom-doerr** [comment]
@etewiah Aider seems to display the token sent for the requests that were rejected. Your context of 114k tokens sent 8 times results in 114k * 8 = 912k token sent. I'm not even that bothered if it's just a display bug, but I'm worried that I'm actually getting charged the amount Aider displays. I paid $83 yesterday, just for using Aider.
![image](https://github.com/user-attachments/assets/25a90248-5edf-4fc9-ab0b-bd4a726c002d)

**Comment by etewiah** [comment]
@tom-doerr  Thanks for explaining.   I did get charged for close to the amount estimated by aider so it seems the tokens are actually getting sent and there is a bug.

**Comment by reecelikesramen** [comment]
I don't have any screenshots to add right now but I've encountered this issue. I know something is up when the streaming is unusually slow. When this occurs I hit ^C and see what is described above: a high number of tokens sent and a high cost.

**Comment by paul-gauthier** [comment]
If you are getting rate limit errors, then aider will automatically retry a few times. Aider will count up all the tokens in all the retries, but the provider should **not** actually charge you when they return a rate limit error.

The aider token counts and costs are necessarily only *estimates*. Aider can't know exactly how each provider will charge for the messages. If you are concerned, check the billing/usage dashboard with your API provider for actual costs.

**Comment by etewiah** [comment]
Thanks for following up @paul-gauthier .  Would just like to take this chance to say a massive thank you for your work on this.  I know how hard it can be when working on an open source project and issue after issue keeps coming in.  Your work is till very much appreciated.

**Comment by webby-box** [comment]
Unbounded agent loops on edit failures burn tokens — hard-cap retries and force a smaller patch after two fails.
