### ISSUE TITLE
Prompt caching writes

### ISSUE THREAD

**Issue by tom-doerr** [Aider-AI/aider#2492]
### Issue

I enabled caching but have more caching writes than reads, which suggests that caching isn't saving a lot of money. Is there a way to reduce cache writes? 
![image](https://github.com/user-attachments/assets/2238ef56-ff2c-4b28-b7d9-31aa1753643c)

### Version and model info

Aider v0.65.1
Main model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite
output
Weak model: claude-3-5-haiku-20241022
Git repo: .git with 56 files
Repo-map: using 1024 tokens, files refresh
Added data_cleaning.py to the chat.
Added models/neural_network.py to the chat.
Added optimize_hyperparameters.py to the chat.
Added utils/data_utils.py to the chat.
Added utils/optimization.py to the chat.
Added utils/optimization_config.py to the chat.
Restored previous conversation history.
Command Line Args:   --sonnet --vim --analytics --analytics-log analytics.log 
--cache-prompts --cache-keepalive-pings 4

Environment Variables:
  OPENAI_API_KEY:    ...U_UA
  ANTHROPIC_API_KEY: ...egAA

Defaults:
  --model-settings-file:.aider.model.settings.yml
  --model-metadata-file:.aider.model.metadata.json
  --env-file:        /home/tom/git/x_twitter_composio/.env
  --map-refresh:     auto
  --map-multiplier-no-files:2
  --input-history-file:/home/tom/git/x_twitter_composio/.aider.input.history
  --chat-history-file:/home/tom/git/x_twitter_composio/.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --tool-warning-color:#FFA500
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     /home/tom/git/x_twitter_composio/.aiderignore
  --lint-cmd:        []
  --test-cmd:        []
  --encoding:        utf-8
  --voice-format:    wav
  --voice-language:  en

Option settings:
  - aiderignore: /home/tom/git/x_twitter_composio/.aiderignore
  - alias: None
  - analytics: True
  - analytics_disable: False
  - analytics_log: analytics.log
  - anthropic_api_key: ...egAA
  - apply: None
  - apply_clipboard_edits: False
  - assistant_output_color: #0088ff
  - attribute_author: True
  - attribute_commit_message_author: False
  - attribute_commit_message_committer: False
  - attribute_committer: True
  - auto_commits: True
  - auto_lint: True
  - auto_test: False
  - cache_keepalive_pings: 4
  - cache_prompts: True
  - chat_history_file: /home/tom/git/x_twitter_composio/.aider.chat.history.md
  - chat_language: None
  - check_update: True
  - code_theme: default
  - commit: False
  - commit_prompt: None
  - completion_menu_bg_color: None
  - completion_menu_color: None
  - completion_menu_current_bg_color: None
  - completion_menu_current_color: None
  - config: None
  - dark_mode: False
  - detect_urls: True
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - editor: None
  - editor_edit_format: None
  - editor_model: None
  - encoding: utf-8
  - env_file: /home/tom/git/x_twitter_composio/.env
  - exit: False
  - fancy_input: True
  - file: None
  - files: []
  - git: True
  - gitignore: True
  - gui: False
  - input_history_file: /home/tom/git/x_twitter_composio/.aider.input.history
  - install_main_branch: False
  - just_check_update: False
  - light_mode: False
  - lint: False
  - lint_cmd: []
  - list_models: None
  - llm_history_file: None
  - load: None
  - map_multiplier_no_files: 2
  - map_refresh: files
  - map_tokens: None
  - max_chat_history_tokens: None
  - message: None
  - message_file: None
  - model: claude-3-5-sonnet-20241022
  - model_metadata_file: .aider.model.metadata.json
  - model_settings_file: .aider.model.settings.yml
  - openai_api_base: None
  - openai_api_deployment_id: None
  - openai_api_key: ...U_UA
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - read: None
  - restore_chat_history: False
  - show_diffs: False
  - show_model_warnings: True
  - show_prompts: False
  - show_release_notes: None
  - show_repo_map: False
  - skip_sanity_check_repo: False
  - stream: True
  - subtree_only: False
  - suggest_shell_commands: True
  - test: False
  - test_cmd: []
  - tool_error_color: #FF2222
  - tool_output_color: None
  - tool_warning_color: #FFA500
  - upgrade: False
  - user_input_color: #00cc00
  - verbose: False
  - verify_ssl: True
  - vim: True
  - voice_format: wav
  - voice_language: en
  - weak_model: None
  - yes_always: None

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Unfortunately, that's just how caching works. Try not to change the read only files in the chat, as every time they change it will cause a new write.
