### ISSUE TITLE
Make it possible to change the working dir in an session

### ISSUE THREAD

**Issue by tom-doerr** [Aider-AI/aider#2500]
Would love this feature Sonnet 3.5 hallucinated: 
![image](https://github.com/user-attachments/assets/de6def70-6103-4fff-866b-ec3ae56ff23a)

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Can you help me understand why you would want this?

**Comment by tom-doerr** [comment]
I often have scripts or dependencies in other projects/directories. I often find myself doing cat ../scripts/.... or find, grep and so on as a substitute for Aider's repo map. Sometimes I also just would like to switch to another repo to analyze with Aider how I used a library to solve a similar approach before so we can create a similar solution for the current problem.
