### ISSUE TITLE
System message configuration issue 

### ISSUE THREAD

**Issue by tom-doerr** [Aider-AI/aider#2507]
### Issue

# Aider Bug Report: System Message Configuration Issues

## Description
Multiple attempts to configure aider's system message have failed across different approaches. The configuration appears to be problematic with both YAML configuration and command-line arguments, suggesting a deeper issue with how system messages are handled.

## Summary of Issues
1. YAML configuration treats system message as a filename
2. Command-line argument for system message is not recognized
3. No clear documentation on the correct way to configure system messages
4. Error messages are not helpful in identifying the correct configuration method

### Attempt 1 - YAML Configuration with Inline Message
1. Add to aider.conf.yml:
```yaml
system-message: "You are a pair programmer..."
```
Result: File name too long error

### Attempt 2 - YAML with Different Key Format
1. Try different key formats in aider.conf.yml:
```yaml
system_message: "..."
system-message: "..."
```
Result: Same file name too long error

### Attempt 3 - External File Reference in YAML
1. Create system message file (aider.system.txt)
2. Reference in aider.conf.yml:
```yaml
system-message-file: aider.system.txt
```
Result: Configuration not recognized

### Attempt 4 - Direct File Path in YAML
1. Update aider.conf.yml:
```yaml
system-message: /home/tom/git/dotfiles/aider.system.txt
```
Result: Treated as literal message text

### Attempt 5 - Command Line Argument
1. Create a system message file (aider.system.txt) with the desired prompt
2. Create an arguments file (aider.args) containing: `--system-message=/path/to/aider.system.txt`
3. Run aider with: `aider $(cat aider.args)`

## Current Behavior
1. When using YAML configuration with inline message:
```
OSError: [Errno 36] File name too long: 'You are a pair programmer...'
```

2. When using command line argument:
```
aider: error: unrecognized arguments: --system-message=/home/tom/git/dotfiles/aider.system.txt
```

3. When using system-message-file in YAML:
```
Configuration key 'system-message-file' not recognized
```

4. Full help output shows no system message configuration options:
```
usage: aider [-h] [--openai-api-key OPENAI_API_KEY]
             [--anthropic-api-key ANTHROPIC_API_KEY] [--model MODEL] [--opus]
             [--sonnet] [--haiku] [--4] [--4o] [--mini] [--4-turbo]
             ...
```

## Expected Behavior
Aider should accept the system message from the specified file and use it to configure the AI assistant's behavior.

## Environment
- OS: Linux 5.15.0-126-generic (64bit)
- Shell: /bin/bash
- Aider version: v0.65.1
- Main model: claude-3-5-sonnet-20241022

### aider.conf.yml attempts:
1. Initial attempt:
```yaml
model: sonnet
editor: vim
analytics: true
analytics-log: analytics.log
cache-prompts: true
cache-keepalive-pings: 1
max-chat-history-tokens: 10000
system-message: "You are a pair programmer..."
```

2. File reference attempt:
```yaml
system-message: /home/tom/git/dotfiles/aider.system.txt
```

3. Alternative key attempt:
```yaml
system_message: "You are a pair programmer..."
```

### aider.system.txt:
Contains the complete system message:
```
You are a pair programmer that responds to natural language requests...
[Full message content]
```

### aider.args:
Command line argument attempt:
```
--system-message=/home/tom/git/dotfiles/aider.system.txt
```

### Execution Methods Tried:
1. Direct aider execution: `aider`
2. With config file: `aider -c aider.conf.yml`
3. With args file: `aider $(cat aider.args)`
4. Combined: `aider -c aider.conf.yml $(cat aider.args)`

### Version and model info

Aider v0.65.1
Main model: claude-3-5-sonnet-20241022 with diff edit format, prompt cache, infinite
output
Weak model: claude-3-5-haiku-20241022
Git repo: none
Repo-map: disabled
Added dotfiles/aider.args to the chat.
Added dotfiles/aider.conf.yml to the chat.
Added dotfiles/aider.system.txt to the chat.
Added dotfiles/aider_bug_report.md to the chat.
Added dotfiles/aider_issue_template.md to the chat.
Added scripts/task/on_add_project_tags.py to the chat.
Restored previous conversation history.
Command Line Args:   --sonnet --vim --analytics --analytics-log analytics.log 
--cache-prompts --cache-keepalive-pings 1 --max-chat-history-tokens 10000

Environment Variables:
  OPENAI_API_KEY:    ...U_UA
  ANTHROPIC_API_KEY: ...egAA

Defaults:
  --model-settings-file:.aider.model.settings.yml
  --model-metadata-file:.aider.model.metadata.json
  --env-file:        .env
  --map-refresh:     auto
  --map-multiplier-no-files:2
  --input-history-file:.aider.input.history
  --chat-history-file:.aider.chat.history.md
  --user-input-color:#00cc00
  --tool-error-color:#FF2222
  --tool-warning-color:#FFA500
  --assistant-output-color:#0088ff
  --code-theme:      default
  --aiderignore:     .aiderignore
  --lint-cmd:        []
  --test-cmd:        []
  --encoding:        utf-8
  --voice-format:    wav
  --voice-language:  en

Option settings:
  - aiderignore: .aiderignore
  - alias: None
  - analytics: True
  - analytics_disable: False
  - analytics_log: analytics.log
  - anthropic_api_key: ...egAA
  - apply: None
  - apply_clipboard_edits: False
  - assistant_output_color: #0088ff
  - attribute_author: True
  - attribute_commit_message_author: False
  - attribute_commit_message_committer: False
  - attribute_committer: True
  - auto_commits: True
  - auto_lint: True
  - auto_test: False
  - cache_keepalive_pings: 1
  - cache_prompts: True
  - chat_history_file: .aider.chat.history.md
  - chat_language: None
  - check_update: True
  - code_theme: default
  - commit: False
  - commit_prompt: None
  - completion_menu_bg_color: None
  - completion_menu_color: None
  - completion_menu_current_bg_color: None
  - completion_menu_current_color: None
  - config: None
  - dark_mode: False
  - detect_urls: True
  - dirty_commits: True
  - dry_run: False
  - edit_format: None
  - editor: None
  - editor_edit_format: None
  - editor_model: None
  - encoding: utf-8
  - env_file: .env
  - exit: False
  - fancy_input: True
  - file: None
  - files: []
  - git: True
  - gitignore: True
  - gui: False
  - input_history_file: .aider.input.history
  - install_main_branch: False
  - just_check_update: False
  - light_mode: False
  - lint: False
  - lint_cmd: []
  - list_models: None
  - llm_history_file: None
  - load: None
  - map_multiplier_no_files: 2
  - map_refresh: files
  - map_tokens: None
  - max_chat_history_tokens: 10000
  - message: None
  - message_file: None
  - model: claude-3-5-sonnet-20241022
  - model_metadata_file: .aider.model.metadata.json
  - model_settings_file: .aider.model.settings.yml
  - openai_api_base: None
  - openai_api_deployment_id: None
  - openai_api_key: ...U_UA
  - openai_api_type: None
  - openai_api_version: None
  - openai_organization_id: None
  - pretty: True
  - read: None
  - restore_chat_history: False
  - show_diffs: False
  - show_model_warnings: True
  - show_prompts: False
  - show_release_notes: None
  - show_repo_map: False
  - skip_sanity_check_repo: False
  - stream: True
  - subtree_only: False
  - suggest_shell_commands: True
  - test: False
  - test_cmd: []
  - tool_error_color: #FF2222
  - tool_output_color: None
  - tool_warning_color: #FFA500
  - upgrade: False
  - user_input_color: #00cc00
  - verbose: False
  - verify_ssl: True
  - vim: True
  - voice_format: wav
  - voice_language: en
  - weak_model: None
  - yes_always: None

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. These docs may be helpful:

https://aider.chat/docs/usage/conventions.html

https://aider.chat/docs/faq.html#can-i-change-the-system-prompts-that-aider-uses

**Comment by trinib** [comment]
@tom-doerr Hey i came across using `system-message: >-` that works. But openED a issue(question) to see if it would make any difference with conventions.md.

![Image](https://github.com/user-attachments/assets/396840b1-eb21-48ef-8eeb-8d00fc2d623d)
