### ISSUE TITLE
Multiple issues with --no-git option

### ISSUE THREAD

**Issue by iswarpatel123** [Aider-AI/aider#2510]
### Issue

Repo Map gets disabled with --no-git option

<img width="654" alt="image" src="https://github.com/user-attachments/assets/66de49d2-bf8c-436d-8746-4aea0166ebc8">

<img width="592" alt="image" src="https://github.com/user-attachments/assets/89aa12c4-5afa-4596-b688-20877ed53bf1">

Browser can't be used with no-git option

aider --no-git --model openai/gpt-4o --browser

"ValueError: GUI can currently only be used inside a git repo"

**Comment by iswarpatel123** [comment]
Thanks. The first issue is in CLI.

**Comment by paul-gauthier** [comment]
Yes, the repo map only works with git repos.
