### ISSUE TITLE
[Feature] Add proper packaging?

### ISSUE THREAD

**Issue by stone-w4tch3r** [Aider-AI/aider#2521]
### Issue

Currently aider is distributed via pip. While this is very convenient for developers, it can be problematic for users:

1. It requires users to have a proper version of python installed. Issue #1984 shows that this threat is real. Moreover, handling multiple versions of python for compatibilty with aider is not straightforward, especially for users without serious python expertise 
2. This approach assumes that the user is familiar with python and it's packaging. While python is indeed a popular language, there are many software devs who use other platforms and have no experience with python. This is especially true for juniors/newbies who don't understand their own stack, let alone Python. Personally I (a c# dev) remember that when I tried first time to install some software from pip, it caused me to learn ubuntu packaging, virtual environments and finally I gave up on this idea.

So to make aider more user friendly we can package it with all required python versions and dependencies.

Currently I see two approaches, a simple and a complex one:
- pre-download all dynamic dependencies into a final package
  - pros: simple build, minimal changes in existing code, usage of native formats like deb/exe/dmg
  - cons: bigger package size
- package aider with isolated container-like runtime
  - pros: allows to download extensions dynamically and even auto update aider within same container
  - cons: AFAIK no cross-platform solution, more complex packaging process is needed
  
Your thoughts?

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

How would you suggest achieving (1)?

For (2), aider is available via docker.

https://aider.chat/docs/install/docker.html
