### ISSUE TITLE
Feature Request: In-Context Instructions Using `--watch-files` for Typescript/React Components

### ISSUE THREAD

**Issue by hgrias** [Aider-AI/aider#2545]
## Request

Currently, when using the `--watch-files` flag and adding `AI!` comments to Typescript/React files (tsx), we are not allowed to add AI comments within the return statement.

Request: Allow the usage of `AI!` comments within the return statement of the React component using JSX style comments to allow for more granular requests. This would be helpful on components with lots of nested divs/components

## Example

The JSX comment would be directly next to the div/element providing better context for the AI to deal with the request

```jsx
import { Layers3, MessageCircleQuestion, MessageSquare } from "lucide-react";
import { CreateFeedbackDialog } from "../_components/feedback/createFeedbackDialog";

export function ExampleComponent() {
  return (
    <>
      <h1>Example Header</h1>

      {/* Make the grid have 6 columns on large screens and 2 on small screens AI! */}

      <div className="grid grid-cols-1 gap-4">
        <div className="flex items-center gap-4 rounded-lg border p-4 transition-all hover:bg-accent">
          <Layers3 className="h-8 w-8 text-primary group-hover:scale-110" />
          <div>
            <h3 className="font-semibold">Workflow</h3>
            <p className="text-sm text-muted-foreground">
              Use our new workflow
            </p>
          </div>
        </div>
        <div className="flex items-center gap-4 rounded-lg border p-4 transition-all hover:bg-accent">
          <MessageSquare className="h-8 w-8 text-primary group-hover:scale-110" />
          <div>
            <h3 className="font-semibold">Chat</h3>
            <p className="text-sm text-muted-foreground">
              Chat with an assistant
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
```

### Version and model info

Aider v0.67.0
Model: claude-3-5-haiku-20241022 with diff edit format, infinite output
Command Line Args:   --haiku --watch-files --dark-mode

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You can probably just stuff in a `// comment AI!`. Aider will notice, perform the request and then delete the comment.
