### ISSUE TITLE
No email address for concerns on children's privacy

### ISSUE THREAD

**Issue by davidlee-ca** [Aider-AI/aider#2546]
Just a small non-technical omission I came across -- the Privacy Policy currently reads [as follows](https://github.com/Aider-AI/aider/blob/c5dc10e3cddddbb4ecdf1e0f022fdb030fd09719/aider/website/docs/legal/privacy.md?plain=1#L72):

> If you learn that a child has provided us with personal information in violation of this Privacy Policy, then you may alert us at [INSERT EMAIL ADDRESS].

I recommend Aider add an email address for completeness' sake. Thank you.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue. Fix is going to the website now.
