### ISSUE TITLE
Watch file doesn't work for .zsh or .zshrc files

### ISSUE THREAD

**Issue by aweis89** [Aider-AI/aider#2550]
### Issue

Can we possibly add .zsh and/or .zshrc to the list of file [extentions](https://github.com/Aider-AI/aider/blob/ecf8617246112984c5160b412e1228786cc4718b/aider/watch.py#L19)?

Tbh, I wish we didn't limit the filetype extensions. If I'm in a filetype with different comment style, I'd rather `--watch-file` would work for an invalid comment (after all it's just a message to AI) then it not work at all. Not to mention we now need to keep documentation updated with the list of valid file extensions.

Note the current implementation that looks for a `suffix` won't work for `.zshrc` as the `.` needs to be after the first character for it to be included in [path.suffix.lower()](https://github.com/Aider-AI/aider/pull/2551/files#diff-ac6a32dda2f8e4b99af10d77900cb601145f83b1da3e6edee7229c8ff5e77b31R55)

**Comment by paul-gauthier** [comment]
I added those and a few more.
