### ISSUE TITLE
Command hooks for better editor integaration

### ISSUE THREAD

**Issue by aweis89** [Aider-AI/aider#2557]
### Issue

It would be awesome if we can add configurable hook commands for Aider to run at different points in the file modification lifecycle for editor integrations.

Being able to run a command after edits are triggered can be used to:
 - Show a git interface to view diffs or modify changes (aider's reliance on git enables usage of tons of tools and existing plugins for interacting with it's changes).
 - Send a notification that the edit has been made or an error popup notifying the user of any potential issues using their IDE's interface.

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

You could probably use the lint and test hooks. 

https://aider.chat/docs/usage/lint-test.html

**Comment by aweis89** [comment]
Oh thanks, that's a neat idea and will definitely give that a try!

I'm wondering however whether I'll need to suppress any error output of running these hook command (e.x. if it's running a git diff but the user isn't in a git repo or the plugin dependency's for diff viewing isn't installed). Would outputting the error cause aider to assume it's a linting or testing error and try to fix it? Ideally these errors would be outputted to the aider console so it's easy to debug what went wrong if it's not working

**Comment by aweis89** [comment]
> Thanks for trying aider and filing this issue.
> 
> You could probably use the lint and test hooks.
> 
> https://aider.chat/docs/usage/lint-test.html

Oh thanks, that's a neat idea and will definitely give that a try!

I'm wondering however whether I'll need to suppress any error output of running these hook command (e.x. if it's running a git diff but the user isn't in a git repo or the plugin dependency's for diff viewing isn't installed). Would outputting the error cause aider to assume it's a linting or testing error and try to fix it? Ideally these errors would be outputted to the aider console so it's easy to debug what went wrong if it's not working

**Comment by aweis89** [comment]
> Thanks for trying aider and filing this issue.
> 
> You could probably use the lint and test hooks.
> 
> https://aider.chat/docs/usage/lint-test.html

Thank you for that quick response! I was able to make this work for my use-case, I'm fairly happy with the results. However a couple things I discovered while implementing this:

- It would be ideal to have a hook for when aider starts processing the request so we can notify the user the request is being processed (e.x. with a spinner). As a workaround I'm processing the streamed output in the background terminal and displaying that in a corner-panel to indicate activity (which looks kinda neat, but is limiting/hacky if I want to use a spinner instead). I also need to ignore various outputs like control characters, ansi escape sequences and messages when Aider is auto adding files.

- Might also be useful to have hook command that aider is prompting for input. As a workaround, I can check if the output has strings like "(Y)es/(N)o" and bring aider process to the foreground for the user to respond so not a huge deal

- Of course the downside of utilizing the `--lint-cmd` or `--test-cmd` is it will override the user's configured commands. As a workaround, I can have them pass it along as a separate config value in the plugin and append it to the hook command so not a huge deal.

All in all, I think your proposal is definitely workable but if we want first-class support for editor integration having some of these hook commands may be more ideal than these workarounds

**Comment by nikhilachale** [comment]
Revisiting this with a concrete editor/orchestrator integration use case.

[Agent Orchestrator](https://github.com/Untrivial-ai/agent-orchestrator) runs Aider in a managed terminal and displays session activity outside the terminal:

- `working` while Aider is processing an LLM request
- `needs_input` when Aider is waiting at either the main prompt or an interactive confirmation

Aider's existing `--notifications-command` provides a reliable completion/input-ready signal. The missing inverse signal is LLM start. Without it, integrations must parse streamed terminal output, ANSI sequences, and prompt text; that is the fragile hidden contract described above.

The current source already has the natural integration point: `Coder` calls `self.io.llm_started()`, and `InputOutput.llm_started()` sets `bell_on_next_input`.

A minimal API would be:

```text
--llm-started-command COMMAND
AIDER_LLM_STARTED_COMMAND=...
llm-started-command: ...
```

Then an integration can run:

```sh
aider \
  --notifications \
  --llm-started-command "ao hooks aider llm-started" \
  --notifications-command "ao hooks aider notification"
```

This does not require prompt mutation, blocking hooks, or a broad plugin system. It exposes the lifecycle transition Aider already tracks internally, paired with the existing input-ready notification.

Would you be open to reopening this issue for that narrower scope? We can contribute the implementation and tests.
