### ISSUE TITLE
For `/chat-mode` help text places architect mode incorrectly

### ISSUE THREAD

**Issue by reecelikesramen** [Aider-AI/aider#2566]
### Issue

For /chat-mode help the architect mode falls under edit format and has no description.

```
> /chat-mode

Chat mode should be one of these:

- help         : Get help about using aider (usage, config, troubleshoot).
- ask          : Ask questions about your code without making any changes.
- code         : Ask for changes to your code (using the best edit format).

Or a valid edit format:

- architect    : No description
- diff         : A coder that uses search/replace blocks for code modifications.
- diff-fenced  : A coder that uses fenced search/replace blocks for code modifications.
- editor-diff  : No description
- editor-whole : No description
- udiff        : A coder that uses unified diff format for code modifications.
- whole        : A coder that operates on entire files for code modifications.
```

### Version and model info

Aider v0.67.0
Main model: claude-3-5-sonnet-20241022 with architect edit format, prompt cache, infinite output
Editor model: claude-3-5-sonnet-20241022 with editor-diff edit format
Weak model: claude-3-5-haiku-20241022
Git repo: .git with 62 files
Repo-map: using 1024 tokens, files refresh

**Comment by paul-gauthier** [comment]
The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you.
