### ISSUE TITLE
Prompt Caching and Cost Estimation Question

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [Aider-AI/aider#2568]
### Issue

My question is simple, but I cannot find this information looking through the docs or previous issues.

If I have prompt caching enabled via `--cache-prompts` with prompt streaming, I get a warning: `Cost: $0.01 message, $0.01 session. Use --no-stream for accurate caching costs.`.

This this mean that the cost estimate is inaccurate, but caching is still in effect. Or does this mean that the caching is disabled.

Docs reference https://aider.chat/docs/usage/caching.html#usage could be a little be more clear on this topic.

Thanks in advance.

### Version and model info

Aider 0.67.0
Model calude-3-5-sonnet

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Caching is enabled, but caching cost estimates are less accurate with streaming.

**Comment by piotrsynowiec** [comment]
I think that repeating this information " Use --no-stream for accurate caching costs" with every message is unnecessary and bad design. It would be great if it was possible to turn it off, because it's enough to read it once, but with every message - I don't think so.
