### ISSUE TITLE
/add autocomplete is unusably slow in 0.68

### ISSUE THREAD

**Issue by jbellis** [Aider-AI/aider#2615]
### Issue

Something broke and it's autocompleting 100s (1000s?) of files.  Responding to keypresses takes multiple seconds.

![image](https://github.com/user-attachments/assets/bb3b1172-6484-435b-b0fe-af32fa0d4c36)

Interestingly it's specific to /add, if I write `add B` (without the `/`) then it's reasonably quick.

Downgrading to 0.67.0 fixes the problem

### Version and model info

Aider 0.68.0

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

Are you still seeing this in v0.69?

**Comment by jbellis** [comment]
In 0.69 autocomplete is faster and doesn't slow down typing since it waits until I hit tab, but when I do I still see the hundreds of files.  If I were to take a wild guess, maybe it switched from case-sensitive to case-insensitive matching?

**Comment by jbellis** [comment]
> it waits until I hit tab

Not sure what was causing this, I am not seeing it today.
