### ISSUE TITLE
--watch-files doesn't work with Scala files

### ISSUE THREAD

**Issue by pkozikow** [Aider-AI/aider#2624]
### Issue

Scala supports '//' style comments just like Java so it could be added to the corresponding list of file extensions so that "Aider in your IDE" works.

### Version and model info

aider-chat                           0.68.0

**Comment by paul-gauthier** [comment]
This should be fixed in the latest version. You can get it like this:

```
aider --upgrade

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed aider-chat
```

If you have a chance to try it, let me know if it works better for you.

**Comment by lockmeister** [comment]
See #2586
@paul-gauthier  I recommend allowing a user-defined trigger. Or something like `@aider` anywhere within the file.

**Comment by pkozikow** [comment]
That was fast! It works in 0.69.0. Thanks.
