### ISSUE TITLE
Support markdown in watch-files

### ISSUE THREAD

**Issue by idvorkin** [Aider-AI/aider#2627]
### Issue

Watch files is an awesome feature, how can I use it in markdown?

  MD comments are not defined,  but usually I see people embed them with the HTML comment syntax. Perhaps that's a way, parse AI from any comment syntax? 
: 

```md

<!-- Comment here -->

```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The latest version should watch all files, including markdown. Just use one of aiders supported comment formats: 

#

//

--

**Comment by idvorkin** [comment]
Oops - now it works, not sure what I did wrong last time, thanks!

**Comment by idvorkin** [comment]
> Thanks for trying aider and filing this issue.

BTW, I've observed how you handle issues, and you are always a class act when responding! A great role model for others. 

@paul-gauthier
