### ISSUE TITLE
Warning for openrouter/deepseek/deepseek-chat

### ISSUE THREAD

**Issue by NeuralAIM** [Aider-AI/aider#2709]
### Issue

`> aider --model openrouter/deepseek/deepseek-chat`

**Output:**
```
Warning for openrouter/deepseek/deepseek-chat: Unknown context window size and costs, using sane defaults.
Did you mean one of these?
- deepseek/deepseek-chat
- openrouter/deepseek/deepseek-coder
You can skip this check with --no-show-model-warnings                                                                   
https://aider.chat/docs/llms/warnings.html
Open documentation url for more info? (Y)es/(N)o/(D)on't ask again [Yes]:
```

### Version and model info

aider 0.69.1, Windows 11

**Comment by NeuralAIM** [comment]
`> aider --model openrouter/deepseek/deepseek-coder`

```
Aider v0.69.1
Model: openrouter/deepseek/deepseek-coder with diff edit format
Git repo: .git with 4 files
Repo-map: using 1024 tokens, auto refresh
```

`> Test`


```
litellm.NotFoundError: NotFoundError: OpenrouterException - Error code: 404 - {'error': {'message': 'No endpoints found
for this model.', 'code': 404}, 'user_id': '. . .'}
```

**Comment by paul-gauthier** [comment]
Thanks for trying aider and filing this issue.

The fix is available in the main branch. You can get it by installing the latest version from github:

```
aider --install-main-branch

# or...

python -m pip install --upgrade --upgrade-strategy only-if-needed git+https://github.com/Aider-AI/aider.git
```

If you have a chance to try it, let me know if it works better for you. I'm going to close this issue for now, but feel free to add a comment here and I will re-open. Or feel free to file a new issue any time.

**Comment by NeuralAIM** [comment]
@paul-gauthier, check https://github.com/Aider-AI/aider/commit/7efdfe5639a454dcb6738069d7cbbda6c571dc0b
```
"openrouter/deepseek/deepseek-chat": {
    "max_tokens": 4096,
    "max_input_tokens": 32000,
    "max_output_tokens": 4096,
    . . .
```

![image](https://github.com/user-attachments/assets/a59923c4-379b-45ea-b5c9-e1e5ae5d4e10)

**Comment by paul-gauthier** [comment]
Sorry, what are you saying?

**Comment by NeuralAIM** [comment]
> Sorry, what are you saying?

Deepseek-chat has a different context size (66k/8k), but you set it to (32k/4k).
