### ISSUE TITLE
git repo corrupted

### ISSUE THREAD

**Issue by lockmeister** [Aider-AI/aider#2734]
### Issue

When using aider in a very large git repo
I am unable to start aider, I get this error:

`Unable to list files in git repo: index out of range
Is your git repo corrupted?
Unable to read git repository, it may be corrupt?
index out of range`

aider works in other repos on my system. It has worked in that repo in the past.
`git status`, add, commit, push all work from the command line in the problem repo. `git ls-files` works.

Aider version: 0.70.0
Python version: 3.12.3
Platform: Linux-6.8.0-51-generic-x86_64-with-glibc2.39
Python implementation: CPython
Virtual environment: Yes
OS: Linux 6.8.0-51-generic (64bit)
Git version: git version 2.43.0

### Version and model info
tried both deepseek and sonnet

**Comment by lockmeister** [comment]
**Issue Summary - Aider Git Index Error**

**Error Message:**
```
Unable to list files in git repo: index out of range
Is your git repo corrupted?
Unable to read git repository, it may be corrupt?
index out of range
```

**Problem:**
Aider (v0.70.0) was unable to read the git repository's index, despite the repository being healthy (confirmed by `git fsck --full`). The repository is large (6,367 files), which likely contributed to the indexing issue.

**Solution:**
Running two git maintenance commands fixed the issue:
```bash
git gc --prune=now    # Garbage collection, cleaned up 23,686 objects
git repack -ad        # Repacked objects, optimizing repository storage
```

**Why it worked:**
These commands optimized and cleaned up the git repository's object storage, likely resolving an internal indexing issue that was preventing Aider from properly reading the repository structure. The large repository size was a contributing factor.

**Prevention:**
For large repos, Aider recommends:
- Using `--subtree-only` flag to work with subset of repository
- Using `.aiderignore` to exclude files (similar to .gitignore)

**Comment by servetus** [comment]
This reproduces quite nicely with Chromium, if you're looking for a repro.

**Comment by kpm** [comment]
I still get this occasionally in one of my repositories, and its not a large repo at all.  `git gc --prune=now` makes it go away.
