### ISSUE TITLE
Aider does not suspend when doing ctrl+z

### ISSUE THREAD

**Issue by Kreijstal** [Aider-AI/aider#701]
### Issue

I know this is unix only, so not useful for windows, but I'd like to be able to suspend the program when doing ctrl+z just like vim in linux

### Version and model info

aider 0.39.0

**Comment by Kreijstal** [comment]
you did it!

**Comment by fry69** [comment]
Thank you for filing this issue.

If you want to suspend aider while it runs I recommend to run aider inside a terminal multiplexer like tmux.

**Comment by Kreijstal** [comment]
> Thank you for filing this issue.
> 
> If you want to suspend aider while it runs I recommend to run aider inside a terminal multiplexer like tmux.

I do not use tmux, why does it have to run on background all the time anyway?

**Comment by Kreijstal** [comment]
Thank you whoever implemented it
